### ISSUE TITLE
Can FSC-W+ be removed?

### ISSUE THREAD

**Issue by rcoleb** [PankratzLab/auto-fcs#31]
@jlanej - 
This gate doesn't appear to remove / lead to anything - can this be removed or is it being used somehow?

**Comment by jlanej** [comment]
Huh, I guess that would be non-singlets ... and when I get the stats for the gating hierarchy I do see some counts in the FSC-W+ population (where"FSC-W+" count + "Singlets" count should equal "lymph" count)

Ex. 

| Population | Parent    | Count  | ParentCount | METRIC | GATE      | QC    | FlaggedSample |
|------------|-----------|--------|-------------|--------|-----------|-------|---------------|
| boundary   | root      | 139947 | 520693      | count  | AUTOMATIC | FALSE | FALSE         |
| nonDebris  | boundary  | 110036 | 139947      | count  | AUTOMATIC | FALSE | FALSE         |
| lymph      | nonDebris | 84859  | 110036      | count  | AUTOMATIC | FALSE | FALSE         |
| FSC-W+     | lymph     | 1353   | 84859       | count  | AUTOMATIC | FALSE | FALSE         |
| Singlets   | lymph     | 83506  | 84859       | count  | AUTOMATIC | FALSE | FALSE         |
| PE-A+      | Singlets  | 516    | 83506       | count  | AUTOMATIC | FALSE | FALSE         |
| PE-A       | Singlets  | 82990  | 83506       | count  | AUTOMATIC | FALSE | FALSE         |

While it doesn't really lead to anything, it does track what was removed.  Is that not desired ?

**Comment by rcoleb** [comment]
I'll ask Devon if she wants to keep it there or not.  We can also hide it from view if it's useful but not needed for annotations.

**Comment by jlanej** [comment]
Nodes and children can be hidden if desired !

```
#gs is a GatingSet
setNode(gs,"FSC-W+",FALSE)
```

**Comment by jlanej** [comment]
```R
panel1NodesToHide = c("CD8/HLA-DR+", "CD4/HLA-DR+", "FSC-W+")
```
