### ISSUE TITLE
Some Singlets don't appear to have a gate?

### ISSUE THREAD

**Issue by rcoleb** [PankratzLab/auto-fcs#32]
@jlanej 

Is this because the entirety of the population is being included?

**Comment by jlanej** [comment]
@rcoleb 

> Is this because the entirety of the population is being included?

I believe so - I've had a couple cases where a gate was not plotted/was missing. But, after adjusting the [tailgate tolerance](https://github.com/PankratzLab/auto-fcs/blob/dbc86d299b2d8d75932c877023f7358a591b4811/explore/openCyto/lymph.dev.d.csv#L5) (how "wide" the selection is), the gate starts to reappear at the edge of the data. So, my interpretation was that everything was included. In this case, the singlet gate would just be the bounds of the data.

**Comment by rcoleb** [comment]
That's what I suspected - thanks!
