### ISSUE TITLE
DC NK MONO PANEL 2

### ISSUE THREAD

**Issue by jlanej** [PankratzLab/auto-fcs#55]
Looks like there are fortessa specific CD3/CD19 gates required, similar to #45 

Before:

![image-9](https://user-images.githubusercontent.com/6052453/32119664-92e5c32c-bb1b-11e7-8e69-511f6a3e8187.png)

<img width="886" alt="screen shot 2017-10-27 at 1 30 51 pm" src="https://user-images.githubusercontent.com/6052453/32119676-9b0c07fa-bb1b-11e7-9069-41cc6c51c482.png">

(Seems like a similar histogram issue as #52 however)

![image-10](https://user-images.githubusercontent.com/6052453/32119745-d92e3d82-bb1b-11e7-9494-7976f9545425.png)
<img width="886" alt="screen shot 2017-10-27 at 1 41 04 pm" src="https://user-images.githubusercontent.com/6052453/32119976-8c3c5314-bb1c-11e7-8566-8a830c748db5.png">

**Comment by jlanej** [comment]
After, fortessa specific, will see how this performs for #56, keeping in mind #42.

<img width="886" alt="screen shot 2017-10-27 at 2 01 43 pm" src="https://user-images.githubusercontent.com/6052453/32120771-752b60cc-bb1f-11e7-855b-3a2dffd7b45b.png">

**Comment by jlanej** [comment]
Currently going to skip CD3 adjustment for panel2 fortessa, looks pretty decent.

**Comment by erincassidy** [comment]
Also I went ahead and looked at the DC NK MONO gate and there seems to be a few minor issues too:

Too high on CD19 axis:
![image](https://user-images.githubusercontent.com/33880355/33783510-b800acf8-dc22-11e7-8aa4-31fcfc275735.png)

F1638718
2016-08-26_PANEL_2_HB-app_setting_reset_Group_one_Clt-D_003
F1632105

too low on CD19 axis:
F1636226

And then this gem (very unusual):
![image](https://user-images.githubusercontent.com/33880355/33783469-916733f0-dc22-11e7-9f65-19eae24a837d.png)
