### ISSUE TITLE
CD8  x-axis refinement 

### ISSUE THREAD

**Issue by jlanej** [PankratzLab/auto-fcs#63]
#54 introduced post-processing of the CD4- x-axis gate following primary detection. Needs a little tweaking, as current method does not appear to dynamically allocate a gate range.

**Comment by jlanej** [comment]
Possible solution is to use tailgate on the CD4 axis within the initial CD8+CD4- population. When a single defined population is detected the tailgate typically matches (or exceeds) the initial CD4- x-axis gate. However, when there is a dense blur (or multiple clusters), tailgate will shrink the CD4- gate.

Afters from #54 :

<img width="400" alt="screen shot 2017-11-17 at 1 25 25 pm" src="https://user-images.githubusercontent.com/6052453/32965257-9f689c74-cb9b-11e7-9c68-a601f1624cb6.png">
<img width="400" alt="screen shot 2017-11-17 at 1 21 04 pm" src="https://user-images.githubusercontent.com/6052453/32965258-9f7b3316-cb9b-11e7-9d2c-3d5f0560e136.png">

<img width="400" alt="screen shot 2017-11-17 at 1 31 34 pm" src="https://user-images.githubusercontent.com/6052453/32965289-adf1adb2-cb9b-11e7-8ab3-c7a5e145e593.png">


Next step will be adding a boolean gate that will prevent the tailgate CD4- location from passing the initial CD4- gate - as is an issue in F1637410_033 above, and the following:

<img width="323" alt="screen shot 2017-11-17 at 1 42 33 pm" src="https://user-images.githubusercontent.com/6052453/32965767-42685d14-cb9d-11e7-9a52-1d9bc460a682.png">
<img width="322" alt="screen shot 2017-11-17 at 1 42 13 pm" src="https://user-images.githubusercontent.com/6052453/32965768-427822bc-cb9d-11e7-9725-12d9c1d65194.png">
<img width="380" alt="screen shot 2017-11-17 at 1 42 03 pm" src="https://user-images.githubusercontent.com/6052453/32965769-42897cf6-cb9d-11e7-903c-ab285e005a24.png">

So, the maximum CD4- gate will be the initial

**Comment by jlanej** [comment]
Examples of applying the boolean ("final" CD8+CD4- highlighted in black). Note that we are now taking the intersection of the primary and secondary CD4- gates. May need to extend the tailgate threshold a bit, but possibly works better than #54 

![1](https://user-images.githubusercontent.com/6052453/32967337-e854087c-cba2-11e7-98de-2d2b8c3f28a5.gif)
![2](https://user-images.githubusercontent.com/6052453/32967338-e866ff04-cba2-11e7-9a75-72f75e51dbd7.gif)
![3](https://user-images.githubusercontent.com/6052453/32967339-e87a92bc-cba2-11e7-8235-03bf0dd7d9c6.gif)

**Comment by jlanej** [comment]
Closing for now, will submit new issue after review

**Comment by erincassidy** [comment]
John could you verify that these samples have two distinct CD8+ populations? I'm having trouble "trusting" the software when I look at images like this:

![image](https://user-images.githubusercontent.com/33880355/33443393-13216e54-d5bd-11e7-8305-7aa64ae51b80.png)

![image](https://user-images.githubusercontent.com/33880355/33443742-f13b004c-d5bd-11e7-95ff-616019cb04cb.png)

![image](https://user-images.githubusercontent.com/33880355/33444346-a9e303d2-d5bf-11e7-9b2f-6796af73d38a.png)

**Comment by jlanej** [comment]
Oh yeah, never trust! I'll check these out in a bit more detail.

**Comment by jlanej** [comment]
### Current method
I'm putting two images for each example above (and I'm guessing the additional examples in #73 are similar). The first is the broad overview of all TCells, and the second zooms in on the x-axis gate in question. Overall I can see definitely what is being called, although the level of distinctness is debatable. 


<img width="886" alt="screen shot 2017-11-30 at 11 35 31 am" src="https://user-images.githubusercontent.com/6052453/33446333-4a5d8c10-d5c5-11e7-9e26-1ebbaea52427.png">
<img width="886" alt="screen shot 2017-11-30 at 11 35 55 am" src="https://user-images.githubusercontent.com/6052453/33446336-4f43e814-d5c5-11e7-89c9-3f6bdfd5754c.png">
<img width="886" alt="screen shot 2017-11-30 at 11 37 44 am" src="https://user-images.githubusercontent.com/6052453/33446341-546b979c-d5c5-11e7-9050-fc102844171c.png">
<img width="886" alt="screen shot 2017-11-30 at 11 37 57 am" src="https://user-images.githubusercontent.com/6052453/33446344-5701bdc4-d5c5-11e7-9b75-f0a310ee27e4.png">
<img width="886" alt="screen shot 2017-11-30 at 11 52 17 am" src="https://user-images.githubusercontent.com/6052453/33446347-5933027e-d5c5-11e7-81f4-e7cc458dfefd.png">
<img width="886" alt="screen shot 2017-11-30 at 11 52 29 am" src="https://user-images.githubusercontent.com/6052453/33446355-5cc66f70-d5c5-11e7-91ea-8d7f7123ee72.png">


A couple options to solve:

1. We can consider these false positives and decrease the sensitivity of the peak detection (see below)
2. Transition to using the Helper T gate for cytotoxic CD4- definitions and not try to trim double populations

### Post reduction in sensitivity

<img width="886" alt="screen shot 2017-11-30 at 12 01 19 pm" src="https://user-images.githubusercontent.com/6052453/33446745-a66722ae-d5c6-11e7-97be-e5cc95fb451d.png">
<img width="886" alt="screen shot 2017-11-30 at 12 01 28 pm" src="https://user-images.githubusercontent.com/6052453/33446746-a89a55b4-d5c6-11e7-867c-70c1be0f9933.png">
<img width="886" alt="screen shot 2017-11-30 at 12 03 55 pm" src="https://user-images.githubusercontent.com/6052453/33446748-a9f88bba-d5c6-11e7-87e9-04f67cf2e076.png">
<img width="886" alt="screen shot 2017-11-30 at 12 04 12 pm" src="https://user-images.githubusercontent.com/6052453/33446750-ab6b4e74-d5c6-11e7-80fa-ffa1f8858880.png">
<img width="886" alt="screen shot 2017-11-30 at 12 05 50 pm" src="https://user-images.githubusercontent.com/6052453/33446829-e751cf44-d5c6-11e7-840e-77e7bdc31cbf.png">
<img width="886" alt="screen shot 2017-11-30 at 12 06 10 pm" src="https://user-images.githubusercontent.com/6052453/33446833-e8e48ed2-d5c6-11e7-8c91-a6c85cdea0c7.png">


- note that we will still detect populations like below. Is that still desired? And should we move forward with the reduced sensitivity model ?
<img width="886" alt="screen shot 2017-11-30 at 12 11 59 pm" src="https://user-images.githubusercontent.com/6052453/33447081-be197040-d5c7-11e7-8c11-dff72db62053.png">
<img width="886" alt="screen shot 2017-11-30 at 12 12 14 pm" src="https://user-images.githubusercontent.com/6052453/33447083-bf8c89da-d5c7-11e7-9948-f08af6440288.png">

**Comment by erincassidy** [comment]
As long as the sensitivity is high enough to detect two distinct populations (as shown in F1652719), decreasing the sensitivity should produce the right result for the three samples above (and ones similar to it!) 

So move forward with solution 1.

**Comment by jlanej** [comment]
Cool sounds good! And we can keep the sensitivity in mind when scanning through the next batch (since we may still have some stragglers).
