### ISSUE TITLE
Bcell subsets - IgD axis

### ISSUE THREAD

**Issue by jlanej** [PankratzLab/auto-fcs#64]
- currently using tailgate to assign IgD+/- without limiting to  CD27-. 
- new strategy will be tailgate IgD+/- with 2 possible distributions, within CD27- only

**Comment by jlanej** [comment]
![image-2](https://user-images.githubusercontent.com/6052453/33080246-328999e6-ce9d-11e7-9beb-3149b69e0149.png)
![image](https://user-images.githubusercontent.com/6052453/33080248-329ac8d8-ce9d-11e7-95d8-f456baa46de7.png)

**Comment by ztflaten** [comment]
Flowjo example

![image](https://user-images.githubusercontent.com/33128106/33096855-0a82af9c-cece-11e7-9878-c439f4e72181.png)

**Comment by jlanej** [comment]
Before:

<img width="886" alt="screen shot 2017-11-21 at 3 33 58 pm" src="https://user-images.githubusercontent.com/6052453/33098104-ceb9e080-ced1-11e7-9713-72ce0fb2e87d.png">
<img width="886" alt="screen shot 2017-11-21 at 3 35 57 pm" src="https://user-images.githubusercontent.com/6052453/33098120-d849a40a-ced1-11e7-8c46-7c740bfe1e88.png">

**Comment by jlanej** [comment]
Little bit improved.
<img width="886" alt="screen shot 2017-11-21 at 5 01 38 pm" src="https://user-images.githubusercontent.com/6052453/33101426-d84410d8-cedd-11e7-94a6-273d2ec19f00.png">
<img width="886" alt="screen shot 2017-11-21 at 5 02 27 pm" src="https://user-images.githubusercontent.com/6052453/33101427-d8763cb6-cedd-11e7-8d5b-5efd7bf9199d.png">

**Comment by jlanej** [comment]
Closing for now and will review, although will likely need a tweak for ghost populations

**Comment by ztflaten** [comment]
I don't think this is worth opening a new issue for. I'm annotating ~250 bcell subset samples so you'll have that for ones that need some tweaking but this one is way off

![image](https://user-images.githubusercontent.com/33128106/33291713-60115586-d38c-11e7-8c3d-1bf4f0851695.png)

This is the first one I've come across like this

**Comment by ztflaten** [comment]
Here's where it should be for reference

![image](https://user-images.githubusercontent.com/33128106/33291745-809e5aba-d38c-11e7-8f03-f75c8f49f1db.png)

**Comment by jlanej** [comment]
@ztflaten yeah I had seen some of the "ghost" populations previously - I'll try putting a bound on the range for where the gate will appear to prevent this.

**Comment by jlanej** [comment]
Before:
<img width="886" alt="screen shot 2017-11-29 at 2 54 07 pm" src="https://user-images.githubusercontent.com/6052453/33398673-6367bf74-d515-11e7-9bc2-03c89a4e7efe.png">

**Comment by jlanej** [comment]
Testing a max-value filter:

<img width="886" alt="screen shot 2017-11-29 at 2 55 13 pm" src="https://user-images.githubusercontent.com/6052453/33398694-709f11e2-d515-11e7-8724-de90a6a7c04a.png">

**Comment by jlanej** [comment]
Actually limiting to CD27- for initial ranging, plus increased max to 200 seems to maintain previous examples.

<img width="886" alt="screen shot 2017-11-29 at 3 20 40 pm" src="https://user-images.githubusercontent.com/6052453/33399664-0dffb1fa-d519-11e7-9a40-6d00ff80d9d0.png">
<img width="886" alt="screen shot 2017-11-29 at 3 19 22 pm" src="https://user-images.githubusercontent.com/6052453/33399665-0e13909e-d519-11e7-820b-2190f5f33d0f.png">
<img width="886" alt="screen shot 2017-11-29 at 3 18 13 pm" src="https://user-images.githubusercontent.com/6052453/33399666-0e314ddc-d519-11e7-97a1-afb822581231.png">

**Comment by jlanej** [comment]
May need to increase tol to shift IgD slightly more to the left, will re-examine after review of `IgD_HelperT_test_79_64`

**Comment by ztflaten** [comment]
New IgD subsets look pretty good overall. This first one is an obvious change.

![image](https://user-images.githubusercontent.com/33128106/33450970-12982a02-d5d3-11e7-96da-566dd9244602.png)

The below one would be a minor shift, but I'm not 100% that I would move it. I see where I would put it but we were pretty variable with this one manually.

![image](https://user-images.githubusercontent.com/33128106/33451047-4b9ad4d0-d5d3-11e7-9bef-3ae802eefa62.png)


Here's a cool one (well sort of, this person probably has acute lymphoblastic leukemia... but it's pretty treatable as far as leukemia goes...)

![image](https://user-images.githubusercontent.com/33128106/33451189-db786c70-d5d3-11e7-8457-b44cd0960d21.png)

here's the Bcell plot (which is gated properly, just showing that they have way too many Bcells)

![image](https://user-images.githubusercontent.com/33128106/33451386-8594b7e0-d5d4-11e7-8431-7e9e58478540.png)


Shift up the Y axis here

![image](https://user-images.githubusercontent.com/33128106/33451363-7610ca70-d5d4-11e7-99d8-8c1a3a1f1d5a.png)

and here

![image](https://user-images.githubusercontent.com/33128106/33451473-c2a2c6ae-d5d4-11e7-8c8a-d63c49f973b5.png)



Shift X axis to the right

![image](https://user-images.githubusercontent.com/33128106/33451443-b05c65a4-d5d4-11e7-920d-6312c004c951.png)


I think @erincassidy has a few examples that she caught as well.

**Comment by jlanej** [comment]
These are indeed a little bit variable, can't tell if we want to adjust the below or not
<img width="886" alt="screen shot 2017-12-01 at 5 27 24 pm" src="https://user-images.githubusercontent.com/6052453/33508007-92305fd8-d6bd-11e7-8d44-03d0b2efadda.png">
<img width="886" alt="screen shot 2017-12-01 at 5 31 43 pm" src="https://user-images.githubusercontent.com/6052453/33508012-99b1096a-d6bd-11e7-99f2-240b57dab598.png">

**Comment by jlanej** [comment]
`F1635729_043` _almost_ looks too far right, instead of left

**Comment by jlanej** [comment]
Added min data filter of `min=20` to target the ALL sample (although still not great)- can fiddle with the y-axis if we want to do another iteration. 

<img width="886" alt="screen shot 2017-12-01 at 5 57 02 pm" src="https://user-images.githubusercontent.com/6052453/33508643-39e23e06-d6c1-11e7-9fce-38f534e5893a.png">
