### ISSUE TITLE
DC NK MONO tail?

### ISSUE THREAD

**Issue by ztflaten** [PankratzLab/auto-fcs#66]
If the sample has a high enough level events min density works well

![image](https://user-images.githubusercontent.com/33128106/33097572-3fe55ee4-ced0-11e7-9e74-fc7a59cd44a8.png)

Low cell counts not as much

![image](https://user-images.githubusercontent.com/33128106/33097599-50f9f83e-ced0-11e7-841d-59aeae425972.png)

This one is worse

![image](https://user-images.githubusercontent.com/33128106/33097626-619f4cfc-ced0-11e7-9f42-4f42c733c4d0.png)

Possibly setting boundries on both axes then tail gate?

![image](https://user-images.githubusercontent.com/33128106/33097643-741a7f14-ced0-11e7-9791-72560e36c01c.png)

**Comment by jlanej** [comment]
Prior to updating for #74 
<img width="886" alt="screen shot 2017-11-27 at 7 31 57 pm" src="https://user-images.githubusercontent.com/6052453/33298027-b182845e-d3a9-11e7-8f1a-e74ea8f9588d.png">
<img width="886" alt="screen shot 2017-11-27 at 7 31 19 pm" src="https://user-images.githubusercontent.com/6052453/33298028-b19516d2-d3a9-11e7-9883-ce23278ac856.png">
<img width="886" alt="screen shot 2017-11-27 at 7 30 38 pm" src="https://user-images.githubusercontent.com/6052453/33298029-b1a7c066-d3a9-11e7-8f97-f7125e743963.png">

**Comment by jlanej** [comment]
Post updating for #74 - looks a bit better. 
<img width="886" alt="screen shot 2017-11-27 at 8 17 02 pm" src="https://user-images.githubusercontent.com/6052453/33299165-0024d610-d3b0-11e7-881e-5d71ec2731ec.png">


<img width="886" alt="screen shot 2017-11-27 at 8 09 57 pm" src="https://user-images.githubusercontent.com/6052453/33299022-492558a4-d3af-11e7-8167-3435b3b3807c.png">

**Comment by jlanej** [comment]
Closing for now, and will see if still necessary after evaluating #74
