### ISSUE TITLE
Fortessa B-Cell

### ISSUE THREAD

**Issue by erincassidy** [PankratzLab/auto-fcs#67]

**Comment by erincassidy** [comment]
Fortessa CD3 cut off is too aggressive for some files.
![image](https://user-images.githubusercontent.com/33880355/33098267-721c2684-ced2-11e7-9beb-163a6ec7ae6d.png)
![image](https://user-images.githubusercontent.com/33880355/33098333-a6bfeba0-ced2-11e7-928e-0e3c67a2e61e.png)

**Comment by jlanej** [comment]
Looks like the tailgate was erroneously detecting two distributions within CD19+.
- solution will be to allow for two distributions, and if two exist, draw the gate on the right of the second. 
Before:

<img width="886" alt="screen shot 2017-11-22 at 9 51 30 am" src="https://user-images.githubusercontent.com/6052453/33136427-c82fa6ac-cf6a-11e7-987e-30f2bdb28bba.png">
<img width="886" alt="screen shot 2017-11-22 at 9 49 11 am" src="https://user-images.githubusercontent.com/6052453/33136429-c83e6174-cf6a-11e7-9f2d-8e2b80077a29.png">

**Comment by jlanej** [comment]
Potential after using updated tailgate allowing for "2" distributions.
<img width="886" alt="screen shot 2017-11-22 at 9 58 00 am" src="https://user-images.githubusercontent.com/6052453/33136869-e607878e-cf6b-11e7-9bc7-69233fb01119.png">
<img width="886" alt="screen shot 2017-11-22 at 9 58 54 am" src="https://user-images.githubusercontent.com/6052453/33136870-e777dfd8-cf6b-11e7-91da-d112a1592fc2.png">

**Comment by jlanej** [comment]
Had to set data-filtering to occur at 150, to prevent situations like:

Before filtering:
<img width="886" alt="screen shot 2017-11-22 at 10 28 42 am" src="https://user-images.githubusercontent.com/6052453/33140268-18d24ccc-cf75-11e7-892b-c9f558e901e4.png">

After filtering:
<img width="886" alt="screen shot 2017-11-22 at 10 32 14 am" src="https://user-images.githubusercontent.com/6052453/33140283-2042bfe6-cf75-11e7-87c2-a7a62aa14663.png">

**Comment by ztflaten** [comment]
Here's an r23 with this problem still. Low cell count though

![image](https://user-images.githubusercontent.com/33128106/33283314-02eeb472-d371-11e7-8e6a-d7dce8d8a78c.png)

**Comment by ztflaten** [comment]
The above was the only instance of this occurring in my ~250 samples

**Comment by jlanej** [comment]
Sounds good - there was an easy fix, so I updated.

<img width="886" alt="screen shot 2017-11-27 at 1 14 31 pm" src="https://user-images.githubusercontent.com/6052453/33284537-10128dfa-d375-11e7-9d7b-5c77357f5e0f.png">

**Comment by jlanej** [comment]
Still appears to be happening after r24
![2017-02-14_panel_1_dhs_group_one_f1653084_017 fcs tcells__cd3 _cd19-_](https://user-images.githubusercontent.com/6052453/33330803-7c99cd5c-d425-11e7-9df8-9fba94e4b364.png)

**Comment by jlanej** [comment]
Another tailgate parameter update gets more improvement. Ill keep monitoring this population as there may be some more stragglers. 

<img width="886" alt="screen shot 2017-11-28 at 11 56 57 am" src="https://user-images.githubusercontent.com/6052453/33335713-6d0c15c6-d433-11e7-83bf-870cd0160497.png">

![2017-02-27_panel_1_dhs_group_one_f1653141_026 fcs tcells__cd3 _cd19-_](https://user-images.githubusercontent.com/6052453/33335735-7c0dac88-d433-11e7-8972-c75945f000fe.png)
