### ISSUE TITLE
CD14, 3 WAY SPLIT

### ISSUE THREAD

**Issue by ztflaten** [PankratzLab/auto-fcs#68]
In Flowjo gate differentiate MONOS from the DC NK in a two way plot of CD14 and CD20 and for most samples we get this:

![image](https://user-images.githubusercontent.com/33128106/33102618-408f45e0-cee3-11e7-9ce1-4ed766f82f35.png)

Which looks like this as a flowjo histogram:

![image](https://user-images.githubusercontent.com/33128106/33102659-65910856-cee3-11e7-9103-519b25cbf96f.png)

In the annotator we something like this (note this isn't the same sample but the separation looks similar enough to the flowjo example that I'm confident in how "I" would gate it)

![image](https://user-images.githubusercontent.com/33128106/33102700-98e33af8-cee3-11e7-9ae1-4e72f30a36d1.png)

So we do have splitting into 3 gates, and the boundary for the CD14+ seems appropriate, but the 'excluded' (CD14 MID?) isn't covering as much. 

![image](https://user-images.githubusercontent.com/33128106/33102804-1f5bff20-cee4-11e7-80bc-b1f7e35ead70.png)

It seems to be the majority case that the CD14+ boundary is good and the lower bound of the CD14 MID needs to be... lowered.

**Comment by ztflaten** [comment]
However there does seem to be cases where the two peaks are close enough together that the current version calls it correctly

![image](https://user-images.githubusercontent.com/33128106/33102885-862df8d4-cee4-11e7-9294-6338f940897d.png)

I'm not sure how to have OC differentiate between these cases (obvious CD14 MID vs minimal CD14 MID)

Here's another one that looks good

![image](https://user-images.githubusercontent.com/33128106/33103000-2a869c38-cee5-11e7-90ab-16f5c1e80c27.png)

One that needs to have the CD14- boundary shifted down

![image](https://user-images.githubusercontent.com/33128106/33103020-5827f6fa-cee5-11e7-8748-408a0c46b543.png)

**Comment by ztflaten** [comment]
Opposite case, good CD14- placement, bad CD14+

![image](https://user-images.githubusercontent.com/33128106/33103069-95153e24-cee5-11e7-9388-7354bc051126.png)

**Comment by jlanej** [comment]
Will start with tweaking the below:

<img width="886" alt="screen shot 2017-11-27 at 10 33 07 am" src="https://user-images.githubusercontent.com/6052453/33277578-93acf8f6-d35e-11e7-82b4-170bb393958f.png">

**Comment by jlanej** [comment]
Possible tailgate-based solution with 2 expected distributions (will require boolean gate for final)

<img width="886" alt="screen shot 2017-11-27 at 10 51 03 am" src="https://user-images.githubusercontent.com/6052453/33278381-0382a12e-d361-11e7-96da-5075a819fb13.png">

**Comment by jlanej** [comment]
Had to simplify a bit for cases where the middle population is not as clear

<img width="886" alt="screen shot 2017-11-27 at 11 02 52 am" src="https://user-images.githubusercontent.com/6052453/33279030-ce82daa0-d362-11e7-82fb-372f4128a808.png">

**Comment by jlanej** [comment]
Next will be to limit situations like below - likely just need to refine primary CD14 mindensity gate
<img width="886" alt="screen shot 2017-11-27 at 11 29 22 am" src="https://user-images.githubusercontent.com/6052453/33280087-8f1e9f80-d366-11e7-97e9-96a825953bbb.png">

**Comment by jlanej** [comment]
mindensity limit from 90 -> 100 may fix 

<img width="886" alt="screen shot 2017-11-27 at 11 33 19 am" src="https://user-images.githubusercontent.com/6052453/33280181-dbee2330-d366-11e7-9270-a8c23deee27e.png">

**Comment by jlanej** [comment]
result of the update on a few examples:

<img width="400" alt="screen shot 2017-11-27 at 11 44 27 am" src="https://user-images.githubusercontent.com/6052453/33280760-c67fbd0e-d368-11e7-8b44-4e1c0c5089ed.png">
<img width="400" alt="screen shot 2017-11-27 at 11 43 32 am" src="https://user-images.githubusercontent.com/6052453/33280761-c68e414e-d368-11e7-9a0f-a798200156e6.png">
<img width="400" alt="screen shot 2017-11-27 at 11 42 45 am" src="https://user-images.githubusercontent.com/6052453/33280762-c69ed482-d368-11e7-9757-fb623513f3dc.png">
<img width="400" alt="screen shot 2017-11-27 at 11 41 46 am" src="https://user-images.githubusercontent.com/6052453/33280763-c6b41a2c-d368-11e7-9770-de06d68e4c92.png">
<img width="400" alt="screen shot 2017-11-27 at 11 41 04 am" src="https://user-images.githubusercontent.com/6052453/33280764-c6c204d4-d368-11e7-83ab-6da5efc67243.png">
<img width="400" alt="screen shot 2017-11-27 at 11 40 11 am" src="https://user-images.githubusercontent.com/6052453/33280765-c6dd5b94-d368-11e7-94fc-5f980d80b6c0.png">
<img width="400" alt="screen shot 2017-11-27 at 11 35 51 am" src="https://user-images.githubusercontent.com/6052453/33280766-c6edf210-d368-11e7-935c-49755ca66f75.png">

**Comment by ztflaten** [comment]
Three way splitting on r24 looks solid. Occasionally I get 'ghosted' CD14+ cut offs

(Below is the cd14- plot but its the easiest way to really see where cd14+ is being drawn)

![image](https://user-images.githubusercontent.com/33128106/33340500-d952e7ce-d441-11e7-9990-4225ee32709a.png)

Which looks like this for monocytes

![image](https://user-images.githubusercontent.com/33128106/33340522-ead68906-d441-11e7-93ff-fa333701686d.png)

**Comment by ztflaten** [comment]
Aside from the ghosted samples I don't see any other issues. This is going to end up being a boolean gate now, correct?

**Comment by jlanej** [comment]
> This is going to end up being a boolean gate now, correct 

Yup both the "final" CD14+ and CD14- populations will be coming from a boolean gate.

**Comment by jlanej** [comment]
Note:

ghosted samples - can set better gate range to prevent. Current is `gate_range=c(100,200)`

**Comment by ztflaten** [comment]
How will boolean gating work for the cd14+ subset? From what I was seeing the current placement of cd14+ boundary is pretty good and boolean on cd14- with the shaded gate would be right.

**Comment by jlanej** [comment]
Yeah the CD14+ boundary is usually pretty good, but could just prevent issues like this https://github.com/PankratzLab/auto-fcs/issues/60#issuecomment-342910963 (note this is from a previous version of the splitting) - although may not be required

**Comment by jlanej** [comment]
@ztflaten do you happen to have a few more examples of the "ghosts", the above seems to be fixed with upstream improvements. 

<img width="886" alt="screen shot 2017-12-04 at 3 57 35 pm" src="https://user-images.githubusercontent.com/6052453/33578430-1cf2f59a-d90c-11e7-86ae-b3668cd1524b.png">

**Comment by ztflaten** [comment]
Let me check

**Comment by ztflaten** [comment]
r24 would be the most recent version for that, right?

**Comment by jlanej** [comment]
Yup, should be

**Comment by ztflaten** [comment]
Looks like
F1652523
F1638549
F1652578
F1652965
F1652753

Out of that set. Not sure if that adds any more to your list

**Comment by jlanej** [comment]
Few before -some were fixed from upstream improvements, but looks like just need to shift mindensity gate range to the left a bit, currently gate_range=c(100,200)
<img width="886" alt="screen shot 2017-12-04 at 4 39 21 pm" src="https://user-images.githubusercontent.com/6052453/33580153-b73310c2-d911-11e7-9202-5c0796dc4a64.png">
<img width="886" alt="screen shot 2017-12-04 at 4 38 43 pm" src="https://user-images.githubusercontent.com/6052453/33580154-b7414c14-d911-11e7-96a2-d63472e59bd6.png">
<img width="886" alt="screen shot 2017-12-04 at 4 37 38 pm" src="https://user-images.githubusercontent.com/6052453/33580155-b751abfe-d911-11e7-86cb-01e058b69c6b.png">
<img width="886" alt="screen shot 2017-12-04 at 4 35 34 pm" src="https://user-images.githubusercontent.com/6052453/33580156-b764dbfc-d911-11e7-9414-ba68b3ca37ee.png">
<img width="886" alt="screen shot 2017-12-04 at 4 34 45 pm" src="https://user-images.githubusercontent.com/6052453/33580157-b77917b6-d911-11e7-9011-510f7185241e.png">

**Comment by jlanej** [comment]
Able to fix ghost examples, will verify on a few others. 
<img width="886" alt="screen shot 2017-12-04 at 4 50 27 pm" src="https://user-images.githubusercontent.com/6052453/33580561-4f3056c2-d913-11e7-966e-75785355f2f8.png">
<img width="886" alt="screen shot 2017-12-04 at 4 49 46 pm" src="https://user-images.githubusercontent.com/6052453/33580562-4f447a26-d913-11e7-937a-97282423acc5.png">
<img width="886" alt="screen shot 2017-12-04 at 4 48 47 pm" src="https://user-images.githubusercontent.com/6052453/33580563-4f576168-d913-11e7-9264-144e1bfc1792.png">
<img width="886" alt="screen shot 2017-12-04 at 4 48 04 pm" src="https://user-images.githubusercontent.com/6052453/33580564-4f90660c-d913-11e7-8029-c45fb71f39a0.png">
<img width="886" alt="screen shot 2017-12-04 at 4 47 33 pm" src="https://user-images.githubusercontent.com/6052453/33580565-4fa379a4-d913-11e7-9014-8febd1c51e03.png">

**Comment by jlanej** [comment]
min data filter on tailgate was causing some samples to be over-trimmed, removing in favor of a simpler/possibly more robust mindensity adjustment. 

Results from current ghosts and previous examples:


<img width="300" alt="screen shot 2017-12-04 at 8 10 12 pm" src="https://user-images.githubusercontent.com/6052453/33586472-2e572310-d92f-11e7-9738-ecb8ea68483c.png">
<img width="300" alt="screen shot 2017-12-04 at 8 09 32 pm" src="https://user-images.githubusercontent.com/6052453/33586473-2e65cb0e-d92f-11e7-9015-6517a1b8ad13.png">
<img width="300" alt="screen shot 2017-12-04 at 8 08 58 pm" src="https://user-images.githubusercontent.com/6052453/33586474-2e762012-d92f-11e7-8477-2c2a492c2f9e.png">
<img width="300" alt="screen shot 2017-12-04 at 8 08 22 pm" src="https://user-images.githubusercontent.com/6052453/33586475-2e8626ec-d92f-11e7-8c6e-d4c87832e0a0.png">
<img width="300" alt="screen shot 2017-12-04 at 8 07 41 pm" src="https://user-images.githubusercontent.com/6052453/33586476-2e96e176-d92f-11e7-8046-24ec68a452d7.png">
<img width="300" alt="screen shot 2017-12-04 at 8 07 01 pm" src="https://user-images.githubusercontent.com/6052453/33586478-2ea5fae4-d92f-11e7-982c-b8b1c7f11b09.png">
<img width="300" alt="screen shot 2017-12-04 at 8 06 32 pm" src="https://user-images.githubusercontent.com/6052453/33586479-2eb8eb36-d92f-11e7-8a8d-34217d11154a.png">
<img width="300" alt="screen shot 2017-12-04 at 8 06 02 pm" src="https://user-images.githubusercontent.com/6052453/33586480-2ec9ce88-d92f-11e7-8c8b-297593a448e6.png">
<img width="300" alt="screen shot 2017-12-04 at 8 04 56 pm" src="https://user-images.githubusercontent.com/6052453/33586481-2eda5e9c-d92f-11e7-8fdc-9719d31bc844.png">
<img width="300" alt="screen shot 2017-12-04 at 8 04 15 pm" src="https://user-images.githubusercontent.com/6052453/33586482-2ef5e270-d92f-11e7-8375-c65a511857c3.png">
<img width="300" alt="screen shot 2017-12-04 at 8 03 19 pm" src="https://user-images.githubusercontent.com/6052453/33586483-2f102f40-d92f-11e7-8f92-669a6367c753.png">
<img width="300" alt="screen shot 2017-12-04 at 8 03 16 pm" src="https://user-images.githubusercontent.com/6052453/33586484-2f266616-d92f-11e7-8abb-c17dce510997.png">
<img width="300" alt="screen shot 2017-12-04 at 8 02 26 pm" src="https://user-images.githubusercontent.com/6052453/33586485-2f35578e-d92f-11e7-81ed-75f639561bb9.png">
<img width="300" alt="screen shot 2017-12-04 at 8 01 52 pm" src="https://user-images.githubusercontent.com/6052453/33586486-2f5558a4-d92f-11e7-8e6f-0be45fac7b58.png">

**Comment by ztflaten** [comment]
Caught transition population here

![image](https://user-images.githubusercontent.com/33128106/33675452-37007102-da78-11e7-8f40-ac4e46a0e7b7.png)

Here too but the populations don't look as distinct

![image](https://user-images.githubusercontent.com/33128106/33675490-5a82dcf0-da78-11e7-8254-2fc8c4cad4d2.png)

I'll just list IDs that match this case for the rest

F1637678
F1642969 (very few monocytes here...)
F1640762
F1635379 (this one is basically a smear, not sure how to solve that)
F1641504
F1640419
F1635361
F1634048
F1640774
F1640647
F1636473 (This one has a GOOD gate but is wide on the CD14 axis)

**Comment by ztflaten** [comment]
This one sample manages to hit all 3 current issues (#76 #83)

![image](https://user-images.githubusercontent.com/33128106/33677184-882ce2ae-da7d-11e7-95fb-95b30e4c3116.png)

**Comment by jlanej** [comment]
Not sure how much left we want to adjust this one actually -

<img width="886" alt="screen shot 2017-12-06 at 4 53 57 pm" src="https://user-images.githubusercontent.com/6052453/33689731-24bb943a-daa6-11e7-859d-b1aa4d9a0036.png">

**Comment by jlanej** [comment]
Latest ghost issues were all from fortessa, creating fortessa specific filter for tailgate

**Comment by jlanej** [comment]
https://github.com/PankratzLab/auto-fcs/commit/7b56d2b780eb9690b14730385f39ce5d1215e2eb caused an increased rate of ghost creation (although was improving transition population removal for all examples). 
Looking like the fix in https://github.com/PankratzLab/auto-fcs/commit/7fe535ed7ba98293a405e87751d31f97e378d261 may be a decent compromise between ghost creation and improving transition population detection.
