### ISSUE TITLE
L/D panel 1 gate, X including too much on a few samples

### ISSUE THREAD

**Issue by ztflaten** [PankratzLab/auto-fcs#70]
Seems to be relatively infrequent, but occasionally I see one that looks like this

![image](https://user-images.githubusercontent.com/33128106/33280472-cdcac49c-d367-11e7-90ac-343feeb3c199.png)

Where I would move the gate down a bit. 

For comparison a sample with a similar number of positive (dead cells) that has a good cut off on the x axis.

![image](https://user-images.githubusercontent.com/33128106/33280504-f2b29f46-d367-11e7-9281-8f005920245b.png)

And I noticed just now as a proofread this submission that it may be an instrument issue (fortessa was the bad example)

We'll have annotations for this gate on r23

**Comment by ztflaten** [comment]
May not be instrument specific, here's an LSR example

![image](https://user-images.githubusercontent.com/33128106/33280922-3bd2c506-d369-11e7-8b7f-352575a1aec0.png)

Setting a max may fix this issue, second hash mark past 10^3 on our plots might be appropriate.

**Comment by jlanej** [comment]
@ztflaten Are there cases where too much is getting trimmed for this gate, as opposed to too little?

**Comment by ztflaten** [comment]
Erin and I didn't see any in the ~500 we looked at and I haven't seen it in previous versions.

**Comment by jlanej** [comment]
<img width="886" alt="screen shot 2017-11-27 at 4 17 32 pm" src="https://user-images.githubusercontent.com/6052453/33292340-84905932-d38e-11e7-94e7-411bca71ec35.png">
<img width="886" alt="screen shot 2017-11-27 at 4 16 11 pm" src="https://user-images.githubusercontent.com/6052453/33292341-84a239e0-d38e-11e7-9a38-37e8bb3a9db0.png">

**Comment by jlanej** [comment]
Since we don't see cases where we are trimming too much, simply adjust the tailgate tolerance.

<img width="886" alt="screen shot 2017-11-27 at 4 19 39 pm" src="https://user-images.githubusercontent.com/6052453/33292477-fbe7a774-d38e-11e7-81b2-6f41a62b7158.png">


<img width="886" alt="screen shot 2017-11-27 at 4 20 31 pm" src="https://user-images.githubusercontent.com/6052453/33292476-fbda06d2-d38e-11e7-9ef9-804399a3990e.png">

**Comment by jlanej** [comment]
Before after on the good example:
<img width="886" alt="screen shot 2017-11-27 at 4 27 00 pm" src="https://user-images.githubusercontent.com/6052453/33292784-0e7cd6a6-d390-11e7-9256-d71debb59560.png">
<img width="886" alt="screen shot 2017-11-27 at 4 27 56 pm" src="https://user-images.githubusercontent.com/6052453/33292786-102514fa-d390-11e7-8ac5-46babaab9e33.png">

**Comment by jlanej** [comment]
Will see how this performs, and can decrease tolerance if we start chopping too much.
