### ISSUE TITLE
Tcells r23 - LSR

### ISSUE THREAD

**Issue by erincassidy** [PankratzLab/auto-fcs#71]
CD19 is cutting too far into Tcells on a few samples
![image](https://user-images.githubusercontent.com/33880355/33281154-e343b4ee-d369-11e7-91c7-ca0734096909.png)

![image](https://user-images.githubusercontent.com/33880355/33281281-4d3337a8-d36a-11e7-87b2-4b582143e74b.png)

**Comment by jlanej** [comment]
May be a similar quick fix as #67

**Comment by jlanej** [comment]
- tailgate appears to be detecting 2 distributions,  will update expectations.
<img width="886" alt="screen shot 2017-11-27 at 12 12 45 pm" src="https://user-images.githubusercontent.com/6052453/33281888-63133166-d36c-11e7-8d73-420ad4bbec18.png">

**Comment by jlanej** [comment]
The other:
<img width="886" alt="screen shot 2017-11-27 at 12 17 29 pm" src="https://user-images.githubusercontent.com/6052453/33282066-107aa5be-d36d-11e7-9e18-4671262fdbe5.png">

**Comment by jlanej** [comment]
Able to fix situations like this, but the other example may be a bit stranger and has a much higher T-Cell cutoff on the CD19 axis

<img width="886" alt="screen shot 2017-11-27 at 12 19 38 pm" src="https://user-images.githubusercontent.com/6052453/33282436-4c8ac164-d36e-11e7-885e-18ebc07ec76e.png">

**Comment by jlanej** [comment]
Previous fix may have started to include too much. 
![2017-02-22_panel_1_zf_group_one_f1638416_015 fcs tcells__cd3 _cd19-_](https://user-images.githubusercontent.com/6052453/33331069-3626af24-d426-11e7-9b9a-5627879fc8ec.png)

**Comment by ztflaten** [comment]
The above Tcell image shouldn't be an issue. On the few samples that do have cells that are cd3+ and that high on cd19 they're so few that including them shouldn't change much. We can look through panel 1 today

**Comment by jlanej** [comment]
@erincassidy @ztflaten from the example above, does this sample appear to be somewhat of an outlier with a high density of CD3+ high on CD19 ? Just wondering if it is worth targeting this pattern or not. 
![33281154-e343b4ee-d369-11e7-91c7-ca0734096909](https://user-images.githubusercontent.com/6052453/33331443-377b23cc-d427-11e7-9159-d9aed155a16c.png)

**Comment by ztflaten** [comment]
I want to say its a limited issue, we're going through r24 today and we'll have a better idea at the end of the day.

**Comment by ztflaten** [comment]
The cytotoxic cd8 (y axis) gate does need to shifted up in the above though, but I think you're working on that still

**Comment by jlanej** [comment]
> Has this sample been flagged before? 
I don't think so, but this sample has the same problem as the sample in #72. When I fixed that sample (F1635738_024) I ended up seeing more an increase in the "true" CD4-CD8+ population , rather than the  CD4-CD8- population though.

**Comment by jlanej** [comment]
@erincassidy @ztflaten  re this issue, I was able to fix one of the two initial examples above but the other was causing problems. I may have just missed your annotations, but in the latest revision, how often are you seeing Tcells being drastically under-called?

**Comment by ztflaten** [comment]
Erin or Ramya have annotations for r24 panel 1 I believe. I want to say it's pretty infrequent but I would have one of them make the final call

**Comment by erincassidy** [comment]
my r24 annotations did not save but I just ran through the batch and did
not find any samples with Tcells drastically cut off on the CD3 axis.

**Comment by ztflaten** [comment]
![image](https://user-images.githubusercontent.com/33128106/33454040-2fe418be-d5dd-11e7-851b-14515009bda1.png)

![image](https://user-images.githubusercontent.com/33128106/33454068-48ff1308-d5dd-11e7-95ad-d78bf837a88a.png)

![image](https://user-images.githubusercontent.com/33128106/33454095-5e9f87a6-d5dd-11e7-9100-382a66896386.png)

![image](https://user-images.githubusercontent.com/33128106/33454119-73c1b1cc-d5dd-11e7-8bd5-1b072d75358a.png)

![image](https://user-images.githubusercontent.com/33128106/33454221-cf067a9a-d5dd-11e7-93a2-c58cb0eb68ef.png)

This one is wrong for a different reason

![image](https://user-images.githubusercontent.com/33128106/33454277-fc5ceccc-d5dd-11e7-8515-05f2b72e3062.png)

Another one!

![image](https://user-images.githubusercontent.com/33128106/33454366-4279ed22-d5de-11e7-8ec5-1298acba08a0.png)

Hopefully these didn't end up being duplicated... I noticed after scrolling for 10 minutes that it seemed like I was seeing the same sample repeated... I'm not sure how many I actually looked at, whether it was the whole IgDHELPERT file set or not but these are all the ones I saw

**Comment by jlanej** [comment]
Cool looks like a good chunk, I'll split these into Fortessa and LSR (Fortessa will be in #72)

**Comment by jlanej** [comment]
Peak sensitivity works for tailgate too - fixes all examples:

<img width="886" alt="screen shot 2017-11-30 at 7 41 36 pm" src="https://user-images.githubusercontent.com/6052453/33464149-90327124-d606-11e7-87c5-71f44214e332.png">
<img width="886" alt="screen shot 2017-11-30 at 7 40 31 pm" src="https://user-images.githubusercontent.com/6052453/33464150-90409a9c-d606-11e7-8e03-0354f5d5581d.png">
<img width="886" alt="screen shot 2017-11-30 at 7 19 20 pm" src="https://user-images.githubusercontent.com/6052453/33464151-90533b8e-d606-11e7-8da2-5b65ba267199.png">

**Comment by jlanej** [comment]
Still has some issues, 
![2016-01-08_panel_1_hb-appsettingsreset_group_one_ctl-b_005 fcs tcells__cd3 _cd19-_](https://user-images.githubusercontent.com/6052453/33488469-4d153fdc-d676-11e7-8d1c-0ee638d5d4ce.png)

Will add expected peak args back in

**Comment by jlanej** [comment]
![2016-07-13_panel_1_zf_group_two_f1631195_026 fcs tcells__cd3 _cd19-_](https://user-images.githubusercontent.com/6052453/33488654-eea85564-d676-11e7-9f1f-81355d3ac0e0.png)

**Comment by jlanej** [comment]
Added back in num peak args removed in https://github.com/PankratzLab/auto-fcs/commit/c901801e3b9bd2ce4ecab616acc8728f7ad38fd6 , should finalize this.

<img width="886" alt="screen shot 2017-12-01 at 9 12 08 am" src="https://user-images.githubusercontent.com/6052453/33488929-ef4aabec-d677-11e7-81a5-4d414613fb0c.png">

<img width="886" alt="screen shot 2017-12-01 at 9 13 14 am" src="https://user-images.githubusercontent.com/6052453/33488928-ef18fca0-d677-11e7-9836-f875283ab8fe.png">
