### ISSUE TITLE
Tcells Fortessa r23

### ISSUE THREAD

**Issue by ztflaten** [PankratzLab/auto-fcs#72]
Creating a separate issue for this

![image](https://user-images.githubusercontent.com/33128106/33282421-3faff7f2-d36e-11e7-9556-794499dfe775.png)

I've only seen one but the cd3 gate is too high here. I'm guessing it's picking up 2 populations here

**Comment by jlanej** [comment]
@ztflaten I remember looking at this particular sample, I'm going to let this issue sit for a bit unless we find multiple instances of this problem.

**Comment by ztflaten** [comment]
Seems like it's just that one sample out of ~250 that I looked at that fall into this category

**Comment by jlanej** [comment]
Able to fix this if needed with max data filter:

<img width="886" alt="screen shot 2017-11-30 at 11 16 08 am" src="https://user-images.githubusercontent.com/6052453/33444576-48b16102-d5c0-11e7-9fba-e62e6b087675.png">

**Comment by jlanej** [comment]
Hit enough critical mass to test these, and since this and #71 kinda seem relevant to #73, will target these first.  Hopefully things will clean up with a min and max filter
<img width="886" alt="screen shot 2017-11-30 at 4 00 57 pm" src="https://user-images.githubusercontent.com/6052453/33457362-ddc14b5a-d5e7-11e7-96a0-2482d6aa7132.png">
<img width="886" alt="screen shot 2017-11-30 at 4 00 25 pm" src="https://user-images.githubusercontent.com/6052453/33457363-dddcb958-d5e7-11e7-92dd-64c09a3bf85b.png">
<img width="886" alt="screen shot 2017-11-30 at 3 59 11 pm" src="https://user-images.githubusercontent.com/6052453/33457364-ddeee2ae-d5e7-11e7-8e86-9e5b7c2aaea0.png">
<img width="886" alt="screen shot 2017-11-30 at 3 58 04 pm" src="https://user-images.githubusercontent.com/6052453/33457365-de0a9be8-d5e7-11e7-99a8-070204c99109.png">
<img width="886" alt="screen shot 2017-11-30 at 3 56 50 pm" src="https://user-images.githubusercontent.com/6052453/33457366-de2434b8-d5e7-11e7-921e-4c3caa8108aa.png">
<img width="886" alt="screen shot 2017-11-30 at 3 55 07 pm" src="https://user-images.githubusercontent.com/6052453/33457367-de354492-d5e7-11e7-906b-d8378231031a.png">

**Comment by jlanej** [comment]
Looks like it may be an upstream issue for `F1652358_014`
<img width="886" alt="screen shot 2017-11-30 at 4 49 45 pm" src="https://user-images.githubusercontent.com/6052453/33459138-7e63bc54-d5ee-11e7-8a48-ed21ed4a7db7.png">

**Comment by jlanej** [comment]
For now I'm going to call `F1652358_014` an outlier - and will check tomorrow's gates to see if there are more. Almost appears that the lymph shows up in the panel two location.

**Comment by jlanej** [comment]
getting decent results with the examples (and some others) using updated filter and peak sensitivity

<img width="886" alt="screen shot 2017-11-30 at 6 54 22 pm" src="https://user-images.githubusercontent.com/6052453/33462901-03166b70-d600-11e7-8538-23c97a521a09.png">
<img width="886" alt="screen shot 2017-11-30 at 6 53 12 pm" src="https://user-images.githubusercontent.com/6052453/33462902-0327596c-d600-11e7-8bf8-d1c9f7711d3a.png">
<img width="886" alt="screen shot 2017-11-30 at 6 52 30 pm" src="https://user-images.githubusercontent.com/6052453/33462903-03369224-d600-11e7-9a76-ff17f066eae4.png">
<img width="886" alt="screen shot 2017-11-30 at 6 51 12 pm" src="https://user-images.githubusercontent.com/6052453/33462904-0346a8d0-d600-11e7-86f2-50b269b4eb1a.png">
<img width="886" alt="screen shot 2017-11-30 at 6 50 10 pm" src="https://user-images.githubusercontent.com/6052453/33462905-03563494-d600-11e7-868a-187e552e8442.png">
<img width="886" alt="screen shot 2017-11-30 at 6 49 22 pm" src="https://user-images.githubusercontent.com/6052453/33462906-036d1100-d600-11e7-9a20-71ae0c09842c.png">
<img width="886" alt="screen shot 2017-11-30 at 6 48 47 pm" src="https://user-images.githubusercontent.com/6052453/33462907-03817906-d600-11e7-9fae-6f9f74b6615e.png">
<img width="886" alt="screen shot 2017-11-30 at 6 47 38 pm" src="https://user-images.githubusercontent.com/6052453/33462908-0392f60e-d600-11e7-85f3-41ee4f7aa3b5.png">

**Comment by ztflaten** [comment]
@ztflaten comment later with flowjo/subsets

**Comment by ztflaten** [comment]
So we had been noticing this in the Tcell subsets (circled in red)

![image](https://user-images.githubusercontent.com/33128106/33518461-e0fd9138-d75a-11e7-9f50-d984f067f822.png)

And we've pretty much fixed that but as I was checking the Fortessa Tcell gates I was noticing this (red square)...

![image](https://user-images.githubusercontent.com/33128106/33518470-09113094-d75b-11e7-8ff5-647ad99edf2f.png)

... was a semi common theme with the gating, a bit into the 'circle' that is the double negative.

And when it's 'far' we get more of that circled 'debris' in the tcell subset gate. I'll comment later with some flowjo plots on this but.......... we should probably move that over on the cd3 axis a bit.

**Comment by ztflaten** [comment]
Second example

![image](https://user-images.githubusercontent.com/33128106/33518502-8ca273fa-d75b-11e7-9802-29a1267de86d.png)

![image](https://user-images.githubusercontent.com/33128106/33518504-985ddd88-d75b-11e7-99ce-29fc94ec0837.png)

**Comment by jlanej** [comment]
Sounds good - I can update this gate to be a little tighter on the CD3 axis to try to avoid some of that sector.

**Comment by ztflaten** [comment]
More examples where I think the Tcell gate is making it harder on opencyto at the cd4 cd8 level

![image](https://user-images.githubusercontent.com/33128106/33518748-3726be54-d760-11e7-89fc-8721d856ddc3.png)

![image](https://user-images.githubusercontent.com/33128106/33518751-3aef58c0-d760-11e7-8647-0bbac91c6bd7.png)

![image](https://user-images.githubusercontent.com/33128106/33518754-3f186efa-d760-11e7-8649-27603a4b3414.png)

![image](https://user-images.githubusercontent.com/33128106/33518755-43e3b5d4-d760-11e7-8cbd-ad70af2f1b92.png)

**Comment by jlanej** [comment]
First two examples from today in OC:
<img width="886" alt="screen shot 2017-12-02 at 1 06 20 pm" src="https://user-images.githubusercontent.com/6052453/33518843-a0b4ffa6-d761-11e7-80fe-87262029fdec.png">
<img width="886" alt="screen shot 2017-12-02 at 1 02 39 pm" src="https://user-images.githubusercontent.com/6052453/33518844-a0c1f648-d761-11e7-845e-04b7a0efc6a7.png">

**Comment by jlanej** [comment]
After restricting a bit more:
<img width="886" alt="screen shot 2017-12-02 at 1 13 06 pm" src="https://user-images.githubusercontent.com/6052453/33518902-a1f06206-d762-11e7-89a8-d961e9bd9a72.png">
<img width="886" alt="screen shot 2017-12-02 at 1 09 56 pm" src="https://user-images.githubusercontent.com/6052453/33518903-a22b7094-d762-11e7-8378-a2680a209d53.png">

**Comment by ztflaten** [comment]
Can I see how that change affected the tcell subsets? My hope is that it cleans out some of 'mid' cd4 expressors

**Comment by jlanej** [comment]
Seems to work! 

Before:
<img width="500" alt="screen shot 2017-12-02 at 1 27 00 pm" src="https://user-images.githubusercontent.com/6052453/33519048-91c1102c-d764-11e7-9930-eb310ebd9dc6.png">
<img width="500" alt="screen shot 2017-12-02 at 1 25 10 pm" src="https://user-images.githubusercontent.com/6052453/33519049-91d02a9e-d764-11e7-89d6-99abe5819e09.png">

After 
<img width="500" alt="screen shot 2017-12-02 at 1 31 43 pm" src="https://user-images.githubusercontent.com/6052453/33519075-29047906-d765-11e7-870d-05d456cd9757.png">
<img width="500" alt="screen shot 2017-12-02 at 1 30 36 pm" src="https://user-images.githubusercontent.com/6052453/33519076-29136d9e-d765-11e7-9b46-12fe7cc5313d.png">
