### ISSUE TITLE
CD8 y-axis refinement

### ISSUE THREAD

**Issue by erincassidy** [PankratzLab/auto-fcs#73]
CD8 axis is too low:

![image](https://user-images.githubusercontent.com/33880355/33286975-c09b0c5e-d37c-11e7-93ae-891a327b7f64.png)

and too high:

![image](https://user-images.githubusercontent.com/33880355/33287012-dfc4fafe-d37c-11e7-800e-8e22b59715a8.png)

Also, is the boolean gate applied to both CD8 and CD4 axes? 
Zach and I have a few samples where the boolean gate would be better for both axes (see below)

![image](https://user-images.githubusercontent.com/33880355/33287293-df8d397e-d37d-11e7-8585-a9dd75f5c600.png)

**Comment by ztflaten** [comment]
![image](https://user-images.githubusercontent.com/33128106/33287511-839c42c6-d37e-11e7-9fcf-449600ee0276.png)
 Here's one of mine where boolean would be good for both axes

**Comment by ztflaten** [comment]
![image](https://user-images.githubusercontent.com/33128106/33288042-78ba25a6-d380-11e7-8625-66ab0d2ad220.png)

**Comment by jlanej** [comment]
> Also, is the boolean gate applied to both CD8 and CD4 axes?

Good point, we can definitely apply it to the CD4 axis as well as CD8.

**Comment by jlanej** [comment]
@erincassidy @ztflaten As a guesstimate, how common is it for the y-axis to be too high?

**Comment by ztflaten** [comment]
I would say it's fairly rare for the cd8 y axis to be too high

**Comment by ztflaten** [comment]
However, now that I've said that I found another one where the y axis is too high

![image](https://user-images.githubusercontent.com/33128106/33290842-99b46f38-d389-11e7-9b81-e6743efb32fd.png)

**Comment by ztflaten** [comment]
![image](https://user-images.githubusercontent.com/33128106/33290848-a365cec8-d389-11e7-8ce4-1312b9f07790.png)

**Comment by jlanej** [comment]
One of the examples had an upstream issue (sample from #72)

Will check the others for upstream problems as well. 
<img width="886" alt="screen shot 2017-11-29 at 4 07 03 pm" src="https://user-images.githubusercontent.com/6052453/33401606-7d761a00-d51f-11e7-919a-3cc6cecf4855.png">

**Comment by jlanej** [comment]
A few priors:
<img width="886" alt="screen shot 2017-11-29 at 4 26 36 pm" src="https://user-images.githubusercontent.com/6052453/33402415-1ff7a8fa-d522-11e7-947f-1e971d6f076d.png">
<img width="886" alt="screen shot 2017-11-29 at 4 25 45 pm" src="https://user-images.githubusercontent.com/6052453/33402416-20033c92-d522-11e7-9582-aed048445fab.png">
<img width="886" alt="screen shot 2017-11-29 at 4 24 37 pm" src="https://user-images.githubusercontent.com/6052453/33402417-2015706a-d522-11e7-997e-9c0a1d9fecc5.png">
<img width="886" alt="screen shot 2017-11-29 at 4 23 46 pm" src="https://user-images.githubusercontent.com/6052453/33402418-2034f642-d522-11e7-9298-7c532430bf82.png">

**Comment by erincassidy** [comment]
Here are additional CD8 axis adjustments that need to be made:

![image](https://user-images.githubusercontent.com/33880355/33443198-973768d4-d5bc-11e7-9f89-53eac7fefb63.png)

![image](https://user-images.githubusercontent.com/33880355/33443517-64c7463e-d5bd-11e7-827e-6e2f2eb75ed8.png)

![image](https://user-images.githubusercontent.com/33880355/33444081-de11808a-d5be-11e7-92c0-4989368634e9.png)


CD8 increase:
![image](https://user-images.githubusercontent.com/33880355/33443592-99ec84a0-d5bd-11e7-9c8c-681a94e24471.png)


CD4 axis increase? (are there really too distinct populations here?):
![image](https://user-images.githubusercontent.com/33880355/33443393-13216e54-d5bd-11e7-8305-7aa64ae51b80.png)

![image](https://user-images.githubusercontent.com/33880355/33443742-f13b004c-d5bd-11e7-95ff-616019cb04cb.png)

**Comment by jlanej** [comment]
Trying to figure out these double-like populations that are tripping things up.

The two below were suggested to be brought down 
<img width="886" alt="screen shot 2017-12-01 at 1 22 09 pm" src="https://user-images.githubusercontent.com/6052453/33499502-bba71046-d69a-11e7-9a61-e70cd7f2b2ef.png">
<img width="886" alt="screen shot 2017-12-01 at 1 19 38 pm" src="https://user-images.githubusercontent.com/6052453/33499503-bbb9847e-d69a-11e7-9edd-29325a2d7b47.png">

And suggested to be brought up

<img width="886" alt="screen shot 2017-12-01 at 1 29 06 pm" src="https://user-images.githubusercontent.com/6052453/33499731-cb023b28-d69b-11e7-9ad9-56de9f87c70f.png">

<img width="886" alt="screen shot 2017-12-01 at 1 35 38 pm" src="https://user-images.githubusercontent.com/6052453/33499933-9900b716-d69c-11e7-8454-e0325a203b0f.png">

**Comment by jlanej** [comment]
Issue is possibly more to move most y-axis down when finding double populations, and leave as is for some where we wanted to move the y-axis up. 

Some of the down-movers:

<img width="886" alt="screen shot 2017-12-01 at 3 01 49 pm" src="https://user-images.githubusercontent.com/6052453/33503288-c380b160-d6a8-11e7-93c0-b064f8b38f71.png">
<img width="886" alt="screen shot 2017-12-01 at 2 51 24 pm" src="https://user-images.githubusercontent.com/6052453/33503289-c3910d30-d6a8-11e7-8685-4bc9308076fc.png">
<img width="886" alt="screen shot 2017-12-01 at 2 50 32 pm" src="https://user-images.githubusercontent.com/6052453/33503290-c39f6402-d6a8-11e7-8f97-c5fd3a41895e.png">

**Comment by ztflaten** [comment]
Flowjo comparison

F1631959
![image](https://user-images.githubusercontent.com/33128106/33503997-5f9258ea-d6ab-11e7-8ada-541bfa3cd10f.png)

F1632220
![image](https://user-images.githubusercontent.com/33128106/33504022-7b24e6f4-d6ab-11e7-95da-baf5f8443e8e.png)

F1631275
![image](https://user-images.githubusercontent.com/33128106/33504082-b022dd02-d6ab-11e7-8766-e43845881be0.png)

F1652467
![image](https://user-images.githubusercontent.com/33128106/33504057-9814f024-d6ab-11e7-8fbc-ec0c5aeb5eab.png)

Thoughts:
Include it for all. I conveniently have workspaces for these from the first 1000 analysis so I can double check all of them but the fact that Helene and another control both have these 'double' cd8's means we would have included both in the beginning.  Andddd the double population goes away when you use a different cell separation method.

**Comment by jlanej** [comment]
Awesome! Thanks for checking those out - makes this issue a bit easier to target if we consistently want to include. As usual, the fix I have may require another update, but looks decent so far.
