### ISSUE TITLE
Live Single PBMCs panel 2

### ISSUE THREAD

**Issue by erincassidy** [PankratzLab/auto-fcs#74]
We noticed that the DC NK mono population (CD3-,CD19-) is more abundant than we would expect. Looking upstream at the other gates, we noticed that the live single PBMCs histogram was taking only the "high" SSC area cells (below)

 
![image](https://user-images.githubusercontent.com/33880355/33292835-42116108-d390-11e7-9345-10d391d573b1.png)

Zach is uploading some Flowjo images of what this live single PBMC histogram gate does to the percentage of DC NK, Bcell, and Tcell populations.

**Comment by ztflaten** [comment]
So here's a test sample that we played around with

PBMC gate

![image](https://user-images.githubusercontent.com/33128106/33292947-a45b1fa2-d390-11e7-8a14-d16393e51417.png)

A rough approximation of where open cyto puts the 'live single PBMCs' gate (note this is straight from the pbmc gate, so there's likely some dead, cd45- and non single cells in here)
![image](https://user-images.githubusercontent.com/33128106/33293008-dbe22c72-d390-11e7-9fee-f1bc4717a899.png)

and what this subset looks like on the cd3 cd19 plot (note the percentages of all the subsets)

![image](https://user-images.githubusercontent.com/33128106/33293057-11e86606-d391-11e7-9b76-5ed5a983be2b.png)

Now if I shift the live single pbmc gate to include the most abundant peak on the histogram

![image](https://user-images.githubusercontent.com/33128106/33293086-2e864788-d391-11e7-8b1f-b7abe4420dd1.png)

We get this

![image](https://user-images.githubusercontent.com/33128106/33293099-38182028-d391-11e7-8cc4-7641e3609764.png)


I'm not really sure where this gate came from but it either needs to be removed or made to take everything. I was kind of hung up on why such a large population was being cut out and initially thought it was the RBCs but looking at it now it's removing a good number of the lymphocytes gate. This might solve some of the problems we've been having with the dc nk mono gate and apparent 'low cell count' samples

**Comment by erincassidy** [comment]
I think we are going to run into this problem with the non-debris gate too. It looks like most of them are not cutting out the lymphocytes; anywhere the gate position is higher than 50K on the FSC area is cutting out lymphocytes

![image](https://user-images.githubusercontent.com/33880355/33293712-5898ca6c-d393-11e7-87e9-e95ff0389d80.png)

![image](https://user-images.githubusercontent.com/33880355/33293735-6ac11366-d393-11e7-87e9-b34288a1b914.png)

**Comment by ztflaten** [comment]
Yeah both the plots mentioned in this issue need to be changed to include events at 50k for the fsc and ssc. This is what a 'manually' gated pbmc sample looks like on the fsc histogram
![image](https://user-images.githubusercontent.com/33128106/33293947-2a84ca9e-d394-11e7-9d83-612f500571fb.png)

![image](https://user-images.githubusercontent.com/33128106/33293957-30bca2e2-d394-11e7-8896-2e96203a5d8a.png)

If I play with the pbmc gate we can see where each population falls on the fsc-a histogram


Intentionally gating RBC's and 'junk'

![image](https://user-images.githubusercontent.com/33128106/33294021-71fba80c-d394-11e7-9583-7e0daeb582e4.png)

![image](https://user-images.githubusercontent.com/33128106/33294035-78e1d90c-d394-11e7-93f6-533fb9cbffd9.png)

Intentionally gating Lymphocytes (T and B cells)

![image](https://user-images.githubusercontent.com/33128106/33294072-a2d67920-d394-11e7-94ae-694652033dc1.png)

![image](https://user-images.githubusercontent.com/33128106/33294080-aa9d67b8-d394-11e7-8795-abd2bae7c9e9.png)

Intentionally gating DC NK MONOS

![image](https://user-images.githubusercontent.com/33128106/33294116-c56da7f6-d394-11e7-97ea-21e28c3c5cc8.png)

![image](https://user-images.githubusercontent.com/33128106/33294121-cc2209f2-d394-11e7-951b-fedf2c2348bb.png)

This should also be changed ASAP for panel 2. I won't include the effects on the percentages for the CD3 CD19 plot like above but it would be similar as we're excluding lymphocytes

**Comment by jlanej** [comment]
Ah interesting - definitely was worth checking the upstream gates it looks like!  I think I will change the initial panel2 gating to be similar to panel 1 on the FSC-A,SSC-A axis, which should bring the lymph back in to the picture. And I agree that this should help with #66 (where we may not even need to update to tailgate)

**Comment by ztflaten** [comment]
It may be worth trying that out and seeing how it does on a few samples but I would be concerned with doing major revisions to early panel 2 this late in the game. I think fixing the positioning for these two gates to never cut above 50k would solve the issue.

**Comment by jlanej** [comment]
First attempt - which puts a max on the the FSC-A gate at 50K 

FSC-A Before :
<img width="886" alt="screen shot 2017-11-27 at 7 09 54 pm" src="https://user-images.githubusercontent.com/6052453/33297442-a011e1b8-d3a6-11e7-854b-a26e469fd070.png">

FSC-A After: 

<img width="886" alt="screen shot 2017-11-27 at 7 16 45 pm" src="https://user-images.githubusercontent.com/6052453/33297675-f58f541c-d3a7-11e7-9d1f-64c5ef72380f.png">

**Comment by jlanej** [comment]
New version - gates between 45K and 50K mindensity. 

Seems decent overall and appears to be capturing lymph
![2017-02-06_panel_2_zf_group_one_f1652864_010 fcs live_single_pbmcs__ssc-a_fsc-a_](https://user-images.githubusercontent.com/6052453/33323796-2b3f79d2-d413-11e7-8961-aadde7dbf017.png)
![2017-01-26_panel_2_zf_group_two_f1636114_027 fcs live_single_pbmcs__ssc-a_fsc-a_](https://user-images.githubusercontent.com/6052453/33323808-3bc085e4-d413-11e7-90a2-c70a738edce1.png)

Perhaps should allow a lower lower bound however? 

![2017-01-27_panel_2_hb_group_one_f1652690_008 fcs live_single_pbmcs__ssc-a_fsc-a_](https://user-images.githubusercontent.com/6052453/33323814-3fb53c44-d413-11e7-864c-61df608be796.png)

**Comment by ztflaten** [comment]
Go ahead and close this one
