### ISSUE TITLE
Live immune cell gate panel 2

### ISSUE THREAD

**Issue by erincassidy** [PankratzLab/auto-fcs#75]
This gate should be tighter just like panel 1 equivalent

![image](https://user-images.githubusercontent.com/33880355/33293409-4731cb80-d392-11e7-9636-ccef0db0af56.png)

![image](https://user-images.githubusercontent.com/33880355/33293365-2692ec74-d392-11e7-92e6-69e71cb0a182.png)

**Comment by ztflaten** [comment]
Some samples after this edit are starting to get to far into what I suspect is live cell territory, can we set a min boundary at 10^3 for this gate? After that this population should be finished

![image](https://user-images.githubusercontent.com/33128106/33338372-869baf26-d43b-11e7-9369-fe61051e509d.png)

![image](https://user-images.githubusercontent.com/33128106/33338402-9e8dc4de-d43b-11e7-8a57-5a7db933b0ce.png)

**Comment by ztflaten** [comment]
Go ahead and close this one
