### ISSUE TITLE
CD16+CD56+ - flowclust 

### ISSUE THREAD

**Issue by jlanej** [PankratzLab/auto-fcs#76]
flowclust does not appear to be performing well for the CD56+/- gate. May need to transition to mindensity or tailgate

**Comment by ztflaten** [comment]
@jlanej Are you looking for some feedback for the current nk56 lo gate for panel 2? I think I hit most of what I wanted changed on Tuesday but I can run through some at this level and give some feedback.

**Comment by jlanej** [comment]
@ztflaten I saw some poor gates and  just wanted to make a note to go back and look. Nothing has changed recently however.

**Comment by ztflaten** [comment]
Looking at most of them I think minDensity would perform better than the current version. 

![image](https://user-images.githubusercontent.com/33128106/33453620-f3d4f650-d5db-11e7-82f9-8c2eac90ac72.png)


If you set the 'target' range where I drew on the above I think it would be looking pretty good

**Comment by ztflaten** [comment]
And for the most part I'm happy with the CD16 placement

**Comment by jlanej** [comment]
Cool, yeah the flowclust method has been kinda hit-or-miss. Seems to work relatively well for a few populations, but I think plugging in mindensity here will be worth it.

**Comment by jlanej** [comment]
Before with flowClust
<img width="886" alt="screen shot 2017-12-04 at 8 39 05 pm" src="https://user-images.githubusercontent.com/6052453/33587349-544f502a-d933-11e7-97dd-3cf9e72a5d5b.png">
<img width="886" alt="screen shot 2017-12-04 at 8 38 19 pm" src="https://user-images.githubusercontent.com/6052453/33587350-5463c3e8-d933-11e7-995f-aa4e0420876b.png">
<img width="886" alt="screen shot 2017-12-04 at 8 36 57 pm" src="https://user-images.githubusercontent.com/6052453/33587351-54736cee-d933-11e7-90aa-221537497842.png">
<img width="886" alt="screen shot 2017-12-04 at 8 35 20 pm" src="https://user-images.githubusercontent.com/6052453/33587352-54846d8c-d933-11e7-9b60-3b04bd6fc3bc.png">
<img width="886" alt="screen shot 2017-12-04 at 8 34 33 pm" src="https://user-images.githubusercontent.com/6052453/33587353-5491d210-d933-11e7-9e08-511addab6240.png">
<img width="886" alt="screen shot 2017-12-04 at 8 31 58 pm" src="https://user-images.githubusercontent.com/6052453/33587354-54a2affe-d933-11e7-8e3c-b74e92eefe9b.png">

**Comment by jlanej** [comment]
After updating to mindensity, not perfect, but better:

<img width="886" alt="screen shot 2017-12-04 at 8 41 18 pm" src="https://user-images.githubusercontent.com/6052453/33587535-2b2ea352-d934-11e7-8c88-c99270c273e1.png">
<img width="886" alt="screen shot 2017-12-04 at 8 41 57 pm" src="https://user-images.githubusercontent.com/6052453/33587536-2b3f8afa-d934-11e7-87fa-12b8748f9fce.png">
<img width="886" alt="screen shot 2017-12-04 at 8 42 35 pm" src="https://user-images.githubusercontent.com/6052453/33587539-2d5ae51e-d934-11e7-8cea-6e40711946d9.png">
<img width="886" alt="screen shot 2017-12-04 at 8 43 12 pm" src="https://user-images.githubusercontent.com/6052453/33587540-2d719692-d934-11e7-94bd-09b1911ab70a.png">
<img width="886" alt="screen shot 2017-12-04 at 8 43 49 pm" src="https://user-images.githubusercontent.com/6052453/33587541-2d820f9a-d934-11e7-9db4-1aadb1740ca4.png">
<img width="886" alt="screen shot 2017-12-04 at 8 44 21 pm" src="https://user-images.githubusercontent.com/6052453/33587542-2d93b416-d934-11e7-86c7-16bdf8c80d30.png">
<img width="886" alt="screen shot 2017-12-04 at 8 44 47 pm" src="https://user-images.githubusercontent.com/6052453/33587543-2da00266-d934-11e7-9eb0-199381a8d65b.png">
<img width="886" alt="screen shot 2017-12-04 at 8 45 29 pm" src="https://user-images.githubusercontent.com/6052453/33587544-2dacc3fc-d934-11e7-8aa1-12b8de5733fa.png">

**Comment by ztflaten** [comment]
The only issue I'm seeing now in the cd56lo gate is instances like this 

![image](https://user-images.githubusercontent.com/33128106/33672428-cb7454f6-da6f-11e7-9e9b-007166a501b1.png)

Where the CD16 axis is too far up. Which is really an issue here

![image](https://user-images.githubusercontent.com/33128106/33672498-f4e8f7c4-da6f-11e7-9a6c-fe2d4731385a.png)


Where the CD16+ histo gate is too far up. 

This is kind of a rare occurence but my proposed solution would be setting a max on the histogram gate.

Perhaps at this level?

![image](https://user-images.githubusercontent.com/33128106/33672641-524da982-da70-11e7-9aad-6b47500d9322.png)


I'll flip through these and make sure that doesn't cut off any legitimate gates but I would be surprised if it does.

**Comment by ztflaten** [comment]
Here's the above samples cd56lo gate for reference 

![image](https://user-images.githubusercontent.com/33128106/33672717-832779a2-da70-11e7-8c00-40236ae8bb09.png)

**Comment by ztflaten** [comment]
@jlanej  Did you end up using my suggested range for the MinDensity (Looks like I drew in between 0 and partway between 10^4)? The only  other issue is it occasionally dips too low and takes a negative population on the cd56 axis. But I don't know if it's frequent enough to be worth monkeying with. 

We would be targeting samples like this

![image](https://user-images.githubusercontent.com/33128106/33673661-04da1110-da73-11e7-9d74-b91d758fa989.png)

**Comment by ztflaten** [comment]
It does seem to be an infrequent situation. And I'm not sure if there's a clear enough 'negative' population to use some sort of two peak detection rule.

**Comment by jlanej** [comment]
@ztflaten right now the CD16+/- definition is the same gate as the CD16+/- for Non classical and Classical monocytes - and relies on all DC NK MONOCYTES (CD3- CD19) data to get a better estimate (I was having trouble getting consistent CD16 gates at the NK level)

For example, the CD16 gate  here 
<img width="500" alt="screen shot 2017-12-06 at 10 58 25 am" src="https://user-images.githubusercontent.com/6052453/33674349-d94d37aa-da74-11e7-9168-d560f1d53f89.png">

Has the exact same cut point as the CD16 gate here.
<img width="500" alt="screen shot 2017-12-06 at 10 58 59 am" src="https://user-images.githubusercontent.com/6052453/33674372-e89bc91a-da74-11e7-89ba-fb678e8802fa.png">
 
So, adjusting the CD16 gate for CD56LO etc would actually happen upstream. I'll plot the example you sent once I can download the data.

**Comment by jlanej** [comment]
> Did you end up using my suggested range for the MinDensity

Right now I'm using a `gate_range=c(50,125)`, but that is on OC scale which looks to be still to low. I can bump up the min value pretty easily though.

**Comment by ztflaten** [comment]
Ahh ok that makes sense. So now I'm thinking all my current panel 2 issues are basically going to be the same fix. I don't think I have a visualization of the OC plot you have above but I can pretend with the classical monocytes gate.

![image](https://user-images.githubusercontent.com/33128106/33674877-74b1106c-da76-11e7-95db-140a913c99d0.png)

I would shift this one up to where is drawn. I was about to open a new issue for this one but now let me look at the NK plot...

I would probably have my cd16 axis for this one where I drew here

![image](https://user-images.githubusercontent.com/33128106/33674928-a5c08476-da76-11e7-9b40-a65bfeaa1566.png)

And that actually matches where I drew on the monocyte plot so that's fun (I didn't even cheat)

**Comment by ztflaten** [comment]
I'll look through and make sure setting that cd16 max wouldn't screw up any monocyte gates... This might be a bit of a tight rope situation.

**Comment by ztflaten** [comment]
![image](https://user-images.githubusercontent.com/33128106/33675378-f6c5c452-da77-11e7-83a4-69ed1cf3ae02.png)

I'm thinking something like this for the cd16 range

**Comment by jlanej** [comment]
Hah yup! Those two suggestions are directly related. I'll focus on the upstream gate in #83 for CD16 and can bump up the CD56 search space for the y-axis here

**Comment by ztflaten** [comment]
Just posted this one on D_NK_M issue with a good Mono gate

CD56 could be bumped up on this one though

![image](https://user-images.githubusercontent.com/33128106/33676179-9a7bcc0c-da7a-11e7-9abe-126d1859c7fc.png)

@jlanej Is there a way to reference comments in github? Might be useful, I think a lot of these are going to be linked issues.

**Comment by jlanej** [comment]
> Is there a way to reference comments in github?

Yup, If you right click on the timestamp of the comment (highlight below) and copy that link, it will show up as 
"https://github.com/PankratzLab/auto-fcs/issues/76#issuecomment-349718751" when you paste it
<img width="424" alt="screen shot 2017-12-06 at 11 45 25 am" src="https://user-images.githubusercontent.com/6052453/33676364-30ab314a-da7b-11e7-965a-a35faf7bd120.png">

**Comment by ztflaten** [comment]
Perfect just update previous [comment](https://github.com/PankratzLab/auto-fcs/issues/76#issuecomment-349718751)

**Comment by ztflaten** [comment]
Same as [here](https://github.com/PankratzLab/auto-fcs/issues/68#issuecomment-349724837)

![image](https://user-images.githubusercontent.com/33128106/33677239-b2db7ace-da7d-11e7-9db1-58b1a6fd60a2.png)

Good 56 boundary

**Comment by jlanej** [comment]
Closing for now
