### ISSUE TITLE
B cell CD19 axis

### ISSUE THREAD

**Issue by erincassidy** [PankratzLab/auto-fcs#78]
CD19 axis includes too much in a few samples. Not a huge problem in terms of how many samples are affected (3/352 total samples)

CD19 axis increase:
![image](https://user-images.githubusercontent.com/33880355/33340388-99755ad8-d441-11e7-89bd-4be6e2870c49.png)

![image](https://user-images.githubusercontent.com/33880355/33340949-0db057da-d443-11e7-9290-a5478f3abcf6.png)

I know you are aware of the CD3 issue as well. Here are a few IDs to look at from r24:

CD3  increase:
![image](https://user-images.githubusercontent.com/33880355/33340484-d04cd158-d441-11e7-9519-15ff0401f1b4.png)

![image](https://user-images.githubusercontent.com/33880355/33340534-f7dc80a6-d441-11e7-86fc-f21f610855fb.png)

![image](https://user-images.githubusercontent.com/33880355/33340573-1599905c-d442-11e7-82ae-32d4ff3c2c1a.png)

**Comment by jlanej** [comment]
🎉  Looks like the fortessa files will be fixed with r25 update in #67 - hopefully will apply to all others.

<img width="886" alt="screen shot 2017-11-28 at 2 57 03 pm" src="https://user-images.githubusercontent.com/6052453/33343844-6c0db774-d44c-11e7-9565-c4e6d7f7d84a.png">
<img width="886" alt="screen shot 2017-11-28 at 2 55 10 pm" src="https://user-images.githubusercontent.com/6052453/33343845-6c1afbe6-d44c-11e7-8115-d04b3640b434.png">
<img width="886" alt="screen shot 2017-11-28 at 2 41 49 pm" src="https://user-images.githubusercontent.com/6052453/33343846-6c285926-d44c-11e7-97f9-6ab7911d30a6.png">

LSR B-cells - will try adjusting the `adjust` parameter of mindensity, looks like it wasn't finding two distributions and setting to min of the gate range

**Comment by jlanej** [comment]
The two LSR images look like the below in OC

<img width="886" alt="screen shot 2017-11-29 at 10 18 22 am" src="https://user-images.githubusercontent.com/6052453/33397815-783a0018-d512-11e7-933f-d30801494457.png">
<img width="886" alt="screen shot 2017-11-29 at 10 17 38 am" src="https://user-images.githubusercontent.com/6052453/33397816-784ac998-d512-11e7-9aa4-6cea50873ba8.png">

**Comment by erincassidy** [comment]
If this is how the samples look without the suggested CD19 axis increase, the CD19 axis should not be increased.. should probably be decreased

**Comment by jlanej** [comment]
Yeah those are both without the increase, I wasn't quite sure how to pick these apart - since I was also considering that the gate could be here ? Or they may be odd-ish samples. 
<img width="886" alt="test" src="https://user-images.githubusercontent.com/6052453/33399186-2ed03370-d517-11e7-9c9b-b0d4f33fd38e.png">

**Comment by erincassidy** [comment]
These samples are odd. I think the original gates are better than increasing the CD19 axis.

**Comment by jlanej** [comment]
Sounds good - I'll leave the LSR B cell CD19 gate as is for now. We can monitor for more samples like this and target this pattern if needed.

**Comment by erincassidy** [comment]
a good number of samples from CD8_sens_Tcells_71_72_69 need the CD19 axis lowered for Bcells:

![image](https://user-images.githubusercontent.com/33880355/33494102-c54eb4cc-d687-11e7-8c31-1adbe4950b91.png)

![image](https://user-images.githubusercontent.com/33880355/33494163-f3293a52-d687-11e7-8248-6823a0bc6149.png)

**Comment by jlanej** [comment]
👍 I'll see if I can get these down - I'm guessing these slipped by previously since the LSR BCell gate hasn't been updated in a while.

**Comment by erincassidy** [comment]
Sample IDs with the above CD19 issue:

F1631174
F1632151
F1636854
F1636889
F1632402
F1631399
F1631411
F1636645
F1636601

**Comment by jlanej** [comment]
A few before:

<img width="886" alt="screen shot 2017-12-01 at 3 28 26 pm" src="https://user-images.githubusercontent.com/6052453/33506392-538263b0-d6b5-11e7-8542-87201da5669b.png">
<img width="886" alt="screen shot 2017-12-01 at 3 27 22 pm" src="https://user-images.githubusercontent.com/6052453/33506394-539e0232-d6b5-11e7-8f08-bfc56319b87a.png">
<img width="886" alt="screen shot 2017-12-01 at 3 25 21 pm" src="https://user-images.githubusercontent.com/6052453/33506395-53b9f3b6-d6b5-11e7-9bd1-727fc71cf379.png">
<img width="886" alt="screen shot 2017-12-01 at 3 22 44 pm" src="https://user-images.githubusercontent.com/6052453/33506396-53cc8eae-d6b5-11e7-86f3-2688b10a78a8.png">
<img width="886" alt="screen shot 2017-12-01 at 3 14 10 pm" src="https://user-images.githubusercontent.com/6052453/33506397-53df8f4a-d6b5-11e7-9cf0-b6dd57cd833b.png">
<img width="886" alt="screen shot 2017-12-01 at 3 12 42 pm" src="https://user-images.githubusercontent.com/6052453/33506398-53f440ca-d6b5-11e7-96f4-041bc50ba6e0.png">
<img width="886" alt="screen shot 2017-12-01 at 3 10 00 pm" src="https://user-images.githubusercontent.com/6052453/33506399-5404d25a-d6b5-11e7-878f-3186c9eeefb1.png">

**Comment by jlanej** [comment]
Added max filter:
<img width="886" alt="screen shot 2017-12-01 at 4 35 43 pm" src="https://user-images.githubusercontent.com/6052453/33506508-bcc70cb8-d6b5-11e7-9b35-5d544caf79f0.png">
<img width="886" alt="screen shot 2017-12-01 at 4 34 49 pm" src="https://user-images.githubusercontent.com/6052453/33506509-bcdcfb86-d6b5-11e7-93fb-e863511294c4.png">
<img width="886" alt="screen shot 2017-12-01 at 4 24 30 pm" src="https://user-images.githubusercontent.com/6052453/33506510-bcee4ec2-d6b5-11e7-815f-3e33f9f6a4c2.png">
<img width="886" alt="screen shot 2017-12-01 at 4 15 29 pm" src="https://user-images.githubusercontent.com/6052453/33506511-bcfd2fa0-d6b5-11e7-82c1-9c060cefedff.png">
<img width="886" alt="screen shot 2017-12-01 at 3 47 39 pm" src="https://user-images.githubusercontent.com/6052453/33506512-bd10fbca-d6b5-11e7-9d0c-6f5e78191599.png">
<img width="886" alt="screen shot 2017-12-01 at 3 36 33 pm" src="https://user-images.githubusercontent.com/6052453/33506513-bd20697a-d6b5-11e7-96a5-09fda573ade2.png">
<img width="886" alt="screen shot 2017-12-01 at 3 33 27 pm" src="https://user-images.githubusercontent.com/6052453/33506514-bd32c0e8-d6b5-11e7-9611-e1ce3bb0456a.png">
