### ISSUE TITLE
Trim CD4 and CD8 tails of helper T cells - when necessary 

### ISSUE THREAD

**Issue by jlanej** [PankratzLab/auto-fcs#79]
![unnamed](https://user-images.githubusercontent.com/6052453/33396289-ad4490de-d50d-11e7-9718-3b3565fa741b.png)

**Comment by jlanej** [comment]
We currently remove the peninsula - but will trim a bit more. Also will add a CD4 axis trimming step to the helperTs

Before:
<img width="886" alt="screen shot 2017-11-29 at 2 06 07 pm" src="https://user-images.githubusercontent.com/6052453/33396564-80797f28-d50e-11e7-8844-1c3536b51f5b.png">

**Comment by jlanej** [comment]
After, will see how this shakes out for a few hundred samples. 
<img width="886" alt="screen shot 2017-11-29 at 2 15 30 pm" src="https://user-images.githubusercontent.com/6052453/33396977-c7d3eff6-d50f-11e7-9533-3ded2f05a697.png">

For this sample, not much changes - which is good. But may need a boolean gate if there are cases where the CD4 trim runs too far past the mindensity gate
<img width="886" alt="screen shot 2017-11-29 at 2 19 54 pm" src="https://user-images.githubusercontent.com/6052453/33397155-6516f8f8-d510-11e7-8bf4-b0a38b3a0fdc.png">

**Comment by ztflaten** [comment]
I've got a cd4 that's too high on the y (cd8) axis. I've looked through a chunk of the current batch and I would say overall I'm pretty satisfied with the change. There are still a few that I would like to see tighter but I think it would be diminishing returns at this point. 

![image](https://user-images.githubusercontent.com/33128106/33448946-f1ba8cb8-d5cc-11e7-887a-28aaaac93a71.png)

**Comment by ztflaten** [comment]
The above cd4 y axis could potentially be solved by preventing the gate from being higher than the cd8's y axis/lower bound, though I suspect the above is a pretty rare occurrence.

**Comment by jlanej** [comment]
@ztflaten It's a very quick change to adjust these down - as long as you aren't seeing any that are too low I'll make another y-axis adjustment and submit for review tonight. 

In general, how is the x-axis looking ?

**Comment by ztflaten** [comment]
X axis is definitely approved. I haven't seen many where the y axis is too far down so maybe adjusting it would be worth trying.

**Comment by ztflaten** [comment]
This would be one where I feel like the x axis on cd4 could be shifted to the right but both gates marked that as a min density point. Can I see what these look like with the 'fancy' scatter + histogram plot you did with the other issue?

![image](https://user-images.githubusercontent.com/33128106/33449950-e70f84c8-d5cf-11e7-8840-4679dc35cd03.png)

![image](https://user-images.githubusercontent.com/33128106/33450024-25eb25a8-d5d0-11e7-95ea-fa2091303fd2.png)

**Comment by ztflaten** [comment]
I'm not that concerned though as it isn't so far too the left that it's adding in what I would consider double negative and from playing around in flowjo I don't think that effects the distribution of the helper subsets all that much.

**Comment by jlanej** [comment]
Slight adjustment - can bring lower if still needed and doesn't go too far in other samples. If it does go to far down in too many samples, we will revert this change. 



Before:
<img width="886" alt="screen shot 2017-11-30 at 1 05 14 pm" src="https://user-images.githubusercontent.com/6052453/33449803-7a0e0674-d5cf-11e7-92ae-e2cf12346e04.png">

After:
<img width="886" alt="screen shot 2017-11-30 at 1 13 11 pm" src="https://user-images.githubusercontent.com/6052453/33450094-54e79f94-d5d0-11e7-9a30-ecde67133357.png">

**Comment by jlanej** [comment]
@ztflaten for the two examples above ... since the secondary gate went past the original, we are essentially seeing the "boolean" subset in the zoomed versions. 

<img width="886" alt="screen shot 2017-11-30 at 1 26 54 pm" src="https://user-images.githubusercontent.com/6052453/33450714-565b3654-d5d2-11e7-9442-f49bd1f47dad.png">
<img width="886" alt="screen shot 2017-11-30 at 1 26 25 pm" src="https://user-images.githubusercontent.com/6052453/33450715-594cb072-d5d2-11e7-9f34-ceb73d880883.png">

<img width="886" alt="screen shot 2017-11-30 at 1 24 48 pm" src="https://user-images.githubusercontent.com/6052453/33450718-5e51ce7c-d5d2-11e7-96c4-9b4682314fd4.png">
<img width="886" alt="screen shot 2017-11-30 at 1 24 15 pm" src="https://user-images.githubusercontent.com/6052453/33450725-60f68654-d5d2-11e7-85e9-3dfa80f519dd.png">

Right now the y-axis trimming is more restrictive than the x-axis, so we could adjust.

**Comment by erincassidy** [comment]
After seeing what your opencyto gates look like, we don't want to increase the CD4 axis placement. 

I think this issue can be closed.
