### ISSUE TITLE
Tcells CD3 axis- LSR 

### ISSUE THREAD

**Issue by jlanej** [PankratzLab/auto-fcs#80]
These examples were in #71, making a separate issue for these, as requires adjustment of the CD3 axis 
![33451903-0a43b1b6-d5d6-11e7-8190-899fdec5bf77-1](https://user-images.githubusercontent.com/6052453/33486671-9037aa6c-d670-11e7-9b06-1a5ee2d6f367.png)
![33454221-cf067a9a-d5dd-11e7-93a2-c58cb0eb68ef](https://user-images.githubusercontent.com/6052453/33486672-90471b3c-d670-11e7-9c24-216413202cb0.png)

**Comment by jlanej** [comment]
rel #73

**Comment by jlanej** [comment]
Before:
<img width="886" alt="screen shot 2017-12-01 at 10 19 02 am" src="https://user-images.githubusercontent.com/6052453/33491854-18a67e4a-d681-11e7-8276-5f97266d8129.png">
<img width="886" alt="screen shot 2017-12-01 at 9 30 47 am" src="https://user-images.githubusercontent.com/6052453/33491855-18c72474-d681-11e7-9b51-62dde5065ff6.png">

_May_ be able to tighten the search range to prevent.

**Comment by erincassidy** [comment]
gate is too far to the left on CD3 axis

![image](https://user-images.githubusercontent.com/33880355/33619685-7dbaa7de-d9ab-11e7-89fd-f0fa8c8e3b09.png)

**Comment by erincassidy** [comment]
the above Tcell gate makes the downstream cytotoxic tcell gate look like:

![image](https://user-images.githubusercontent.com/33880355/33620063-736fe310-d9ac-11e7-8001-76c94d9c3676.png)

**Comment by jlanej** [comment]
@erincassidy do the upstream gates look OK for `F1631593_028`?

**Comment by ztflaten** [comment]
No, the CD3 axis on the Tcell gate is cutting two far into the double negative. Fixing upstream would fix subsets here
