### ISSUE TITLE
Cytotoxic, X and Y

### ISSUE THREAD

**Issue by ztflaten** [PankratzLab/auto-fcs#81]
Making a new issue for this as the old one's are starting to be a bit cluttered (also the first version of this post didn't submit due to internet issues here so hopefully there aren't two of these later)

![image](https://user-images.githubusercontent.com/33128106/33518703-46a474d0-d75f-11e7-9ae7-3178c85889c6.png)

Have the X axis sensitivity adjustments we've been making for this to gate A or gate B (see above)? Gate B is pretty close to where I think this should end up but it seems neither gate has moved much (although I don't remember exactly how it looked before). 

This one looks like a counter example to the above (in annotator at least) where the whole thing is taken

![image](https://user-images.githubusercontent.com/33128106/33518724-b38731aa-d75f-11e7-9e1f-2ee8817be0b8.png)

**Comment by jlanej** [comment]
> Have the X axis sensitivity adjustments we've been making for this to gate A or gate B (see above)? 

The sensitivity adjustments will only change the gate B location, and doesn't influence Gate A. Currently the sensitivity adjustments are just to prevent gate B being set closer to the Gate A location.

**Comment by jlanej** [comment]
Going to run another batch changing gate B method to tailgate, with 2 peak prior and same sensitivity. This _may_ eliminate the need for any boolean gating on the cytotoxic subset. Also, will allow a more dynamic x-axis range (mindensity has a max for the gate range)

**Comment by jlanej** [comment]
From a quick scan, tailgate seems to be performing decent. After a more complete review we can determine if it consistently outperforms the previous method.

**Comment by erincassidy** [comment]
the gate is completely missing the cytotoxic Tcells here:

![image](https://user-images.githubusercontent.com/33880355/33564925-5ea01f98-d8e1-11e7-8b87-a77bc8193297.png)

![image](https://user-images.githubusercontent.com/33880355/33564972-77e9f988-d8e1-11e7-9616-3943f0855e36.png)

the peak sensitivity might still be too high:

![image](https://user-images.githubusercontent.com/33880355/33565356-8531bc24-d8e2-11e7-8984-ed48a7e10579.png)

![image](https://user-images.githubusercontent.com/33880355/33566259-ff0654c2-d8e4-11e7-8f1f-2771b3fe504f.png)

![image](https://user-images.githubusercontent.com/33880355/33566306-286e2c18-d8e5-11e7-9820-a4cdc8d22012.png)

**Comment by erincassidy** [comment]
To fix the premature cut off of cytotoxic tcells on CD4 axis like below:
![image](https://user-images.githubusercontent.com/33880355/33569721-31c83cda-d8f0-11e7-9359-bb511bf60bd4.png)

Would it be possible to set the minimum value for which a mindensity can be found at 10^3 on CD4 axis?

Some samples might now include a clear second population (below):

![image](https://user-images.githubusercontent.com/33880355/33569824-86286d36-d8f0-11e7-9e64-592cbb58c3c7.png)

but in most samples with clear double populations, the mindensity is found well above 10^3 on CD4 axis:

![image](https://user-images.githubusercontent.com/33880355/33570198-aaf8b08e-d8f1-11e7-9bf0-8db474d8b0cf.png)

**Comment by jlanej** [comment]
Some befores:

<img width="886" alt="screen shot 2017-12-04 at 1 01 48 pm" src="https://user-images.githubusercontent.com/6052453/33570731-610b6b68-d8f3-11e7-8070-3d4ed0823e45.png">
<img width="886" alt="screen shot 2017-12-04 at 1 01 12 pm" src="https://user-images.githubusercontent.com/6052453/33570732-61198ca2-d8f3-11e7-87f9-993d764981fd.png">
<img width="886" alt="screen shot 2017-12-04 at 1 00 11 pm" src="https://user-images.githubusercontent.com/6052453/33570733-612c077e-d8f3-11e7-8f55-09007aaea467.png">
<img width="886" alt="screen shot 2017-12-04 at 12 58 43 pm" src="https://user-images.githubusercontent.com/6052453/33570734-6139c6f2-d8f3-11e7-9579-4317a4e9388f.png">
<img width="886" alt="screen shot 2017-12-04 at 12 57 44 pm" src="https://user-images.githubusercontent.com/6052453/33570736-617e1d8e-d8f3-11e7-99dd-7e78ca899419.png">

Will target the _way_ too far left first, with min data filter.

**Comment by ztflaten** [comment]
Erin just made a comment that might fix the way too far left and some of the other's we're having

**Comment by jlanej** [comment]
@ztflaten @erincassidy Yup! That is the min data filter addition.

**Comment by jlanej** [comment]
@ztflaten @erincassidy just an FYI, we actually have transitioned to using tailgate here for Gate "B" which is a little more suited to the task at hand - placing the gate at the _end_ of the population. With mindensity we had to define an explicit range (which was previously 85-150 in the OC scale), and would default to 150 if two populations were not found, regardless of the data -which can result in truncation. 

Currently, the method tries to do the following. 
1. Find 2 populations, if possible, based on the peak sensitivity (and min/max data filter)
	- If only 1 peak is found, place the gate at the right side of that population
	- If 2 peaks are found, place the gate at the right side of the left most peak. 

And just to make sure, from the example above we will now be trying to skip detecting peaks like this.
Before:
- finds two peaks based on sensitivity and data filters.
<img width="886" alt="screen shot 2017-12-04 at 1 31 20 pm" src="https://user-images.githubusercontent.com/6052453/33572499-c028244c-d8f8-11e7-8ba3-6192e415ef9d.png">
<img width="886" alt="screen shot 2017-12-04 at 1 30 38 pm" src="https://user-images.githubusercontent.com/6052453/33572952-174c7394-d8fa-11e7-93c3-26f180647b01.png">

After:

- finds one peak based on sensitivity and data filters.
	- tailgate benefit is also seen here, since the gate extends past 150
<img width="886" alt="screen shot 2017-12-04 at 1 40 29 pm" src="https://user-images.githubusercontent.com/6052453/33572969-1d601dc6-d8fa-11e7-9596-4a6951448de3.png">

Looks decent to me!

**Comment by jlanej** [comment]
With some more "Afters"
<img width="886" alt="screen shot 2017-12-04 at 1 57 17 pm" src="https://user-images.githubusercontent.com/6052453/33573344-1fec816e-d8fb-11e7-9ec6-b771a74ac83b.png">

<img width="886" alt="screen shot 2017-12-04 at 1 56 32 pm" src="https://user-images.githubusercontent.com/6052453/33573346-2008353a-d8fb-11e7-91f7-7516daf8c0b5.png">
<img width="886" alt="screen shot 2017-12-04 at 1 55 37 pm" src="https://user-images.githubusercontent.com/6052453/33573347-201594e6-d8fb-11e7-80cb-2860a221eccd.png">
<img width="886" alt="screen shot 2017-12-04 at 1 54 45 pm" src="https://user-images.githubusercontent.com/6052453/33573348-20292d08-d8fb-11e7-955f-630e09704937.png">

**Comment by ztflaten** [comment]
This looks promising. Just to clarify, we would be dropping the boolean after this change? That's what we would want based on the images above. I think we should test drive this tomorrow if possible and that will probably be the last look..........

**Comment by jlanej** [comment]
Yup - hopefully no need for any cytotoxic boolean gates, as long as gate "B" is in a decent spot.

**Comment by jlanej** [comment]
Had to tweak once more since to still capture the litmus test. 

<img width="886" alt="screen shot 2017-12-04 at 2 48 44 pm" src="https://user-images.githubusercontent.com/6052453/33575435-411ebf1c-d902-11e7-8391-77750f38678e.png">

But now gets that, plus the above examples.

<img width="886" alt="screen shot 2017-12-04 at 2 47 34 pm" src="https://user-images.githubusercontent.com/6052453/33575456-571f0fc4-d902-11e7-99a6-e7d500e95baf.png">
<img width="886" alt="screen shot 2017-12-04 at 2 46 29 pm" src="https://user-images.githubusercontent.com/6052453/33575457-57331140-d902-11e7-81b7-d0e04679ff1c.png">
<img width="886" alt="screen shot 2017-12-04 at 2 45 34 pm" src="https://user-images.githubusercontent.com/6052453/33575458-575789ee-d902-11e7-9328-2c928f285d1a.png">
<img width="886" alt="screen shot 2017-12-04 at 2 44 23 pm" src="https://user-images.githubusercontent.com/6052453/33575459-576943aa-d902-11e7-8f96-90f0005a26b2.png">
<img width="886" alt="screen shot 2017-12-04 at 2 43 32 pm" src="https://user-images.githubusercontent.com/6052453/33575460-578076f6-d902-11e7-9716-9dc55dc90953.png">
<img width="886" alt="screen shot 2017-12-04 at 2 40 53 pm" src="https://user-images.githubusercontent.com/6052453/33575461-57909b44-d902-11e7-8f85-45371bb0e46f.png">

Also should fix the gates ever showing up _way_ to far left

**Comment by erincassidy** [comment]
These look like the CD4 axis is below 10^3:

![image](https://user-images.githubusercontent.com/33880355/33619593-45ae32e8-d9ab-11e7-98de-b5584e6a2477.png)

![image](https://user-images.githubusercontent.com/33880355/33622161-a2c40802-d9b2-11e7-9295-cb8039542cdf.png)

**Comment by erincassidy** [comment]
we don't the "B" gate any lower than one notch above 10^3 (highlighted in image):

![image](https://user-images.githubusercontent.com/33880355/33631263-af586050-d9cf-11e7-9c1d-99dfadf76de8.png)

**Comment by ztflaten** [comment]
When looking for the min density point, if that wasn't implied already. I don't know if I know of any cases where it called a tail gate below that point either but...

**Comment by jlanej** [comment]
https://github.com/PankratzLab/auto-fcs/issues/81#issuecomment-349104194

**Comment by ztflaten** [comment]
![image](https://user-images.githubusercontent.com/33128106/33632873-9e484046-d9d4-11e7-94cf-821a8dbf41d4.png)

**Comment by ztflaten** [comment]
Would become bad with reversion too quad gate... Maybe that's OK?

![image](https://user-images.githubusercontent.com/33128106/33632934-cb45c384-d9d4-11e7-8e64-8182ab77baf6.png)

**Comment by ztflaten** [comment]
![image](https://user-images.githubusercontent.com/33128106/33633035-1ef115f6-d9d5-11e7-94e7-5da72b8bfca9.png)

**Comment by ztflaten** [comment]
![image](https://user-images.githubusercontent.com/33128106/33633071-39e45756-d9d5-11e7-98f1-1ce8aeb88b79.png)

**Comment by ztflaten** [comment]
![image](https://user-images.githubusercontent.com/33128106/33633232-af1c8e94-d9d5-11e7-89bc-878871c2e51c.png)

**Comment by jlanej** [comment]
<img width="886" alt="screen shot 2017-12-05 at 4 05 12 pm" src="https://user-images.githubusercontent.com/6052453/33633354-1d438954-d9d6-11e7-8ba6-e5d9dd831f15.png">

**Comment by jlanej** [comment]
<img width="886" alt="screen shot 2017-12-05 at 4 05 56 pm" src="https://user-images.githubusercontent.com/6052453/33633378-3656828e-d9d6-11e7-8d8c-f7d6ce15a7f9.png">

**Comment by ztflaten** [comment]
Whole thing
![image](https://user-images.githubusercontent.com/33128106/33633556-eaf66f56-d9d6-11e7-9894-e62a296d7865.png)

**Comment by ztflaten** [comment]
Trimmed

![image](https://user-images.githubusercontent.com/33128106/33633574-fb7df754-d9d6-11e7-9060-06a56cdca6a4.png)

**Comment by ztflaten** [comment]
Just the trimmed gated

![image](https://user-images.githubusercontent.com/33128106/33633616-15705832-d9d7-11e7-9344-9e852f442f70.png)

**Comment by ztflaten** [comment]
Litmus test:

Whole thing

![image](https://user-images.githubusercontent.com/33128106/33633844-c5739cb2-d9d7-11e7-9a9c-7da28244c828.png)

Trimmed

![image](https://user-images.githubusercontent.com/33128106/33633861-d3cbb678-d9d7-11e7-94e7-757a5da53408.png)


Trimmed only

![image](https://user-images.githubusercontent.com/33128106/33633878-e2a677fa-d9d7-11e7-99c6-390486945bc3.png)

**Comment by jlanej** [comment]
New version 
<img width="886" alt="screen shot 2017-12-05 at 4 40 44 pm" src="https://user-images.githubusercontent.com/6052453/33634790-13e111c4-d9db-11e7-89d0-430016f63c83.png">
<img width="886" alt="screen shot 2017-12-05 at 4 42 28 pm" src="https://user-images.githubusercontent.com/6052453/33634866-50e8e984-d9db-11e7-83e8-006f23a1b228.png">

**Comment by ztflaten** [comment]
'Booleaned' helper t cell as the boundary for cytotoxic examples

![image](https://user-images.githubusercontent.com/33128106/33635772-f636915e-d9de-11e7-901e-4cb61165b4a3.png)

This one basically reverts to a quad gate

![image](https://user-images.githubusercontent.com/33128106/33635789-0a97ce74-d9df-11e7-8189-a62cfb601325.png)


![image](https://user-images.githubusercontent.com/33128106/33635824-2b8bc8a6-d9df-11e7-8816-db0c2b926ae5.png)
