### ISSUE TITLE
Cytotoxic x-axis from Helper T

### ISSUE THREAD

**Issue by jlanej** [PankratzLab/auto-fcs#82]
trying a quick test of this method, will default to quadgate (https://github.com/PankratzLab/auto-fcs/commit/73da8a93ff32cf25f9c0b9724e331f746ebb269e) if this gets too complex

**Comment by jlanej** [comment]
Able to extend helper T gate, just need boolean addition:

<img width="886" alt="screen shot 2017-12-05 at 5 47 28 pm" src="https://user-images.githubusercontent.com/6052453/33637098-a6cc3a5a-d9e4-11e7-8a25-0d4f7da7c73d.png">
<img width="886" alt="screen shot 2017-12-05 at 5 48 42 pm" src="https://user-images.githubusercontent.com/6052453/33637099-a6dd1924-d9e4-11e7-9e6c-f5d1a31c2a27.png">

**Comment by jlanej** [comment]
Figured out how to write openCyto plugins, http://opencyto.org/plugins.html
Have the helperT boolean gate working, without actual boolean gates so flowAnnotator can view.

<img width="886" alt="screen shot 2017-12-05 at 8 19 12 pm" src="https://user-images.githubusercontent.com/6052453/33641169-fdf12ccc-d9f9-11e7-8e3f-7faf49bf4b6a.png">
<img width="886" alt="screen shot 2017-12-05 at 8 21 09 pm" src="https://user-images.githubusercontent.com/6052453/33641170-fdff5d42-d9f9-11e7-9e28-0b4eb9ae051e.png">

**Comment by jlanej** [comment]
Given we aren't targeting double populations, I think this is working well. Took a bit of magic, but will see how this performs on a few hundred samples.

<img width="886" alt="screen shot 2017-12-05 at 10 09 17 pm" src="https://user-images.githubusercontent.com/6052453/33644242-3cccf624-da09-11e7-8c8b-f979eb70b12b.png">
<img width="886" alt="screen shot 2017-12-05 at 10 07 45 pm" src="https://user-images.githubusercontent.com/6052453/33644243-3cdb3694-da09-11e7-9a09-da1f1c8dd693.png">
<img width="886" alt="screen shot 2017-12-05 at 10 06 41 pm" src="https://user-images.githubusercontent.com/6052453/33644245-3ceb6c62-da09-11e7-9cd3-cd231898f5ce.png">
<img width="886" alt="screen shot 2017-12-05 at 10 05 59 pm" src="https://user-images.githubusercontent.com/6052453/33644246-3d0203dc-da09-11e7-8b3b-27c9d03aa699.png">
<img width="886" alt="screen shot 2017-12-05 at 10 04 47 pm" src="https://user-images.githubusercontent.com/6052453/33644247-3d17bcc2-da09-11e7-95ec-6c800b13acb3.png">
<img width="886" alt="screen shot 2017-12-05 at 10 03 57 pm" src="https://user-images.githubusercontent.com/6052453/33644248-3d247eb2-da09-11e7-9d05-21a44a2df680.png">
<img width="886" alt="screen shot 2017-12-05 at 10 02 52 pm" src="https://user-images.githubusercontent.com/6052453/33644249-3d3319cc-da09-11e7-9efe-dfea94e03ee3.png">
<img width="886" alt="screen shot 2017-12-05 at 10 01 57 pm" src="https://user-images.githubusercontent.com/6052453/33644250-3d4051d2-da09-11e7-8984-80423aefc386.png">
<img width="886" alt="screen shot 2017-12-05 at 10 00 46 pm" src="https://user-images.githubusercontent.com/6052453/33644251-3d5b6db4-da09-11e7-8b40-3aa11eac8f72.png">
<img width="886" alt="screen shot 2017-12-05 at 9 59 58 pm" src="https://user-images.githubusercontent.com/6052453/33644252-3d796f58-da09-11e7-8599-9608598c8a2a.png">
<img width="886" alt="screen shot 2017-12-05 at 9 59 00 pm" src="https://user-images.githubusercontent.com/6052453/33644253-3d97d0ce-da09-11e7-9f4c-1c7541daf092.png">
<img width="886" alt="screen shot 2017-12-05 at 9 58 00 pm" src="https://user-images.githubusercontent.com/6052453/33644254-3dbcc136-da09-11e7-8901-84a87225692a.png">
<img width="886" alt="screen shot 2017-12-05 at 9 56 34 pm" src="https://user-images.githubusercontent.com/6052453/33644255-3de3c394-da09-11e7-9ec8-c2abb2927f31.png">
<img width="886" alt="screen shot 2017-12-05 at 9 55 43 pm" src="https://user-images.githubusercontent.com/6052453/33644256-3e018532-da09-11e7-89a6-6c5ed5268df0.png">
<img width="886" alt="screen shot 2017-12-05 at 9 55 00 pm" src="https://user-images.githubusercontent.com/6052453/33644257-3e1fcbd2-da09-11e7-8c96-92592bda9f6d.png">
<img width="886" alt="screen shot 2017-12-05 at 9 51 02 pm" src="https://user-images.githubusercontent.com/6052453/33644258-3e413452-da09-11e7-805f-161af6751727.png">
<img width="886" alt="screen shot 2017-12-05 at 9 49 46 pm" src="https://user-images.githubusercontent.com/6052453/33644259-3e79da64-da09-11e7-9784-b62d4592296e.png">
<img width="886" alt="screen shot 2017-12-05 at 9 46 01 pm" src="https://user-images.githubusercontent.com/6052453/33644260-3eadface-da09-11e7-8486-232cc7863db0.png">
<img width="886" alt="screen shot 2017-12-05 at 9 43 45 pm" src="https://user-images.githubusercontent.com/6052453/33644261-3ebc21e4-da09-11e7-849b-4d4a7dfc63e8.png">
<img width="886" alt="screen shot 2017-12-05 at 9 41 18 pm" src="https://user-images.githubusercontent.com/6052453/33644262-3eddf800-da09-11e7-95d3-b8c11f4b715a.png">
<img width="886" alt="screen shot 2017-12-05 at 9 40 22 pm" src="https://user-images.githubusercontent.com/6052453/33644263-3efc9da0-da09-11e7-8c4b-0dffca431381.png">

**Comment by ztflaten** [comment]
Let's give this a shot for the 'final' version.

**Comment by ztflaten** [comment]
This didn't change anything for the Helper tcell gate did it? I've got this one that's a total miss and I don't know if I've seen that happen in a while

![image](https://user-images.githubusercontent.com/33128106/33684353-9dc45528-da93-11e7-9cab-4d49b086c246.png)

**Comment by jlanej** [comment]
Yeah that gate didn't change. The issue is the primary CD4+/- mindensity gate not finding two peaks.  But, this is _extremely_ rare right ?

**Comment by ztflaten** [comment]
I have to think so I haven't seen this gate be off/ghosted in a long long time now

**Comment by jlanej** [comment]
This is the same sample from r23, if I had to guess, there is an upstream issue that is bringing in extra garbage. How do the upstream gates look?
![2017-01-30_panel_1_dhs_group_one_f1652689_006 fcs cytotoxic_tcells-cd8](https://user-images.githubusercontent.com/6052453/33686141-86b1f4de-da99-11e7-9ebf-82c5b66550f8.png)

**Comment by ztflaten** [comment]
Everything looks normal upstream

**Comment by jlanej** [comment]
Hah, well I guess that is good, just a bad gate. If we see 4 or more of these we can adjust, otherwise I'd say we just flag this sample.

**Comment by ztflaten** [comment]
I just flew through the full set (800?) and that's the only one that missed the mark. Probably safe to ignore?

**Comment by jlanej** [comment]
Yup I'd say so - the problem gate hasn't changed in at least 2 months, and you've rarely seen issues like this in other revisions, so likely safe. 

As a note for the future if we ever do want to update:
- Can add a bounded gate range to the initial  CD4+/- mindensity

**Comment by jlanej** [comment]
Histogram to highlight why mindensity missed, single CD4 peak
<img width="886" alt="screen shot 2017-12-06 at 3 42 06 pm" src="https://user-images.githubusercontent.com/6052453/33686970-2e156a38-da9c-11e7-971e-ffd1354b500d.png">
