### ISSUE TITLE
D_NK_M CD16+/- refinement 

### ISSUE THREAD

**Issue by jlanej** [PankratzLab/auto-fcs#83]
CD16+/- may need some slight tuning, and will also help some of the CD16 issues in #76

**Comment by jlanej** [comment]
Current search space is gate_range=c(90,200) , will likely need to bump up the min a bit.
@ztflaten if you have a few more examples where this gate is too low, just set them in this issue

**Comment by jlanej** [comment]
![e](https://user-images.githubusercontent.com/6052453/33675619-c5611cda-da78-11e7-972a-ec687e7b5072.png)
![33](https://user-images.githubusercontent.com/6052453/33675633-d6c09dac-da78-11e7-8b8c-55b698a9ed6e.png)

**Comment by ztflaten** [comment]
Yep here's one but it kind of flies in the face of my CD16 max dreams with it's nice split right at 10^4

![image](https://user-images.githubusercontent.com/33128106/33675646-e0691f46-da78-11e7-8131-4ff7483858d6.png)

**Comment by ztflaten** [comment]
![image](https://user-images.githubusercontent.com/33128106/33676059-4e16b1b0-da7a-11e7-8f3d-4fc9dde1baa4.png)

**Comment by ztflaten** [comment]
Another one that screws up the 10^4 max idea (good gate here)

![image](https://user-images.githubusercontent.com/33128106/33676124-6ffcd9d0-da7a-11e7-940f-2f1d252a4782.png)

**Comment by jlanej** [comment]
Having difficulty with "single" CD16 pops, can for sure adjust min.
<img width="886" alt="screen shot 2017-12-06 at 4 45 53 pm" src="https://user-images.githubusercontent.com/6052453/33689436-0c5ff120-daa5-11e7-87e3-91fab7563f29.png">
<img width="886" alt="screen shot 2017-12-06 at 4 45 00 pm" src="https://user-images.githubusercontent.com/6052453/33689437-0c726f12-daa5-11e7-825a-10d34a979a94.png">
<img width="886" alt="screen shot 2017-12-06 at 4 44 28 pm" src="https://user-images.githubusercontent.com/6052453/33689438-0c7f335a-daa5-11e7-9bd4-e24d116ae8ce.png">
<img width="886" alt="screen shot 2017-12-06 at 4 43 52 pm" src="https://user-images.githubusercontent.com/6052453/33689439-0c8c1de0-daa5-11e7-875b-98af6c672edd.png">

**Comment by jlanej** [comment]
Updated the gate args for mindensity to `gate_range=c(125,220),adjust=1.5`, which will improve the default location of the gate (125 on OC scale) for single peaks. Also allows for the gate to range slightly higher, and with increased sensitivity. Not perfect, but should help.

**Comment by erincassidy** [comment]
Majority of samples look great! 

Two samples are still "ghosting":

![image](https://user-images.githubusercontent.com/33880355/33781302-a9b8b6e4-dc19-11e7-9f95-985130d4b381.png)

![image](https://user-images.githubusercontent.com/33880355/33782114-fa27c0ea-dc1c-11e7-90c7-b166a48d5780.png) (not sure on this one though- might be a weird sample)

Several samples still including intermediate population on CD14 axis (sample IDs of this problem below):
![image](https://user-images.githubusercontent.com/33880355/33781357-ece0e27a-dc19-11e7-9217-8a6d9accf33a.png)

F1638961
F1631435
F1631858
F1638966
2017-10-16_PANEL_2_FORTESSA_ZF_group_one_EC_Ctl-G_023
F1642058
F1632566
F1632515
F1632770
F1634989
F1641791
F1635011
F1632708
F1641978
F1642773
F1638218
F1637924
2017-10-16-PANEL_2_FORTESSA_group_one_ZF_Ctl-F_005

I annotated a few samples with "unsure" because I can't tell where classical monocytes end and non-classical begins...:

![image](https://user-images.githubusercontent.com/33880355/33781869-e1506af0-dc1b-11e7-837c-cce24ad46f9a.png)

![image](https://user-images.githubusercontent.com/33880355/33781895-067a02a0-dc1c-11e7-999b-308610e93951.png)

![image](https://user-images.githubusercontent.com/33880355/33781911-134fd752-dc1c-11e7-826e-1856744b0432.png)

**Comment by jlanej** [comment]
@erincassidy Looks like the "unsure" bunch are the strangely named samples - I'm going to ignore those for now. 

Anyway, I'm going to concentrate on the intermediate population issues

**Comment by erincassidy** [comment]
Okay sounds good.

**Comment by ztflaten** [comment]
I was sort of able to go through some of the zip filed ones. Did we end up splitting the gates on the cd16 axis? There were some I couldn't see the nonclassical gate for.

**Comment by jlanej** [comment]
Not splitting currently. There will be no gate created if there aren't any CD14+CD16+ events. Right now the gate is the created from the min/max of each axis within the nonclassical "search space". This just shows up as a 0 count in the end results. 
![2016-12-22_panel_2_hb_group_one_f1635968_009 fcs classical_monocytes__cd16-_cd14 _](https://user-images.githubusercontent.com/6052453/33786077-4f7dac20-dc2d-11e7-826f-cf582733d781.png)

**Comment by jlanej** [comment]
@erincassidy Could the "ghost" examples above actually be correct ?

From the samples with intermediate issues above, only two are LSR and look like this.

<img width="886" alt="screen shot 2017-12-08 at 3 48 42 pm" src="https://user-images.githubusercontent.com/6052453/33786651-825ca91e-dc2f-11e7-9365-1f71f3370d18.png">
<img width="886" alt="screen shot 2017-12-08 at 3 47 14 pm" src="https://user-images.githubusercontent.com/6052453/33786652-826e8774-dc2f-11e7-85b2-c146dacee091.png">

Which would actually look like "ghosts" if we moved them over

**Comment by jlanej** [comment]
Either way, it looks like the main intermediate issues are isolated to fortessa

**Comment by erincassidy** [comment]
I might have typed in wrong IDs... only two looked like they were ghosting

**Comment by jlanej** [comment]
I _think_ the IDs are correct, was just thinking that if we try to fix these two on the x-axis,  
<img width="886" alt="screen shot 2017-12-08 at 3 48 42 pm" src="https://user-images.githubusercontent.com/6052453/33787085-478b041e-dc31-11e7-8304-a6425ee2b0e2.png">
<img width="886" alt="screen shot 2017-12-08 at 3 47 14 pm" src="https://user-images.githubusercontent.com/6052453/33787086-479e2da0-dc31-11e7-9884-89378096355f.png">

they would kinda end up looking like the ghosts 

![33781302-a9b8b6e4-dc19-11e7-9f95-985130d4b381](https://user-images.githubusercontent.com/6052453/33787110-653431ac-dc31-11e7-8869-ba11b339bc36.png)
![33782114-fa27c0ea-dc1c-11e7-90c7-b166a48d5780](https://user-images.githubusercontent.com/6052453/33787111-654721b8-dc31-11e7-8681-8ed557818512.png)

But, it seems like LSR is typically good overall (so won't be fixing the four above), and instead focusing on the fortessa issues.

**Comment by erincassidy** [comment]
Sorry John I did not read your comment carefully. I agree with you- changing the LSR samples would not be correct.
